// @ctx .context/src/core/parser.ctx
import{readFileSync as e,readdirSync as t,statSync as s,existsSync as n}from"fs";import{join as r,relative as o,resolve as a}from"path";import{parse as i}from"../../vendor/acorn.mjs";import*as l from"../../vendor/walk.mjs";import{shouldExcludeDir as c,shouldExcludeFile as p,parseGitignore as u}from"./filters.js";import{parseTypeScript as f}from"../lang/lang-typescript.js";import{parsePython as d}from"../lang/lang-python.js";import{parseGo as m}from"../lang/lang-go.js";import{parseSQL as h,extractSQLFromString as y,isSQLString as g}from"../lang/lang-sql.js";
const x=[".js",".ts",".tsx",".py",".go",".sql"];
export async function parseFile(e,t){const s={file:t,classes:[],functions:[],imports:[],exports:[]},n=[];
let r;try{r=i(e,{ecmaVersion:"latest",sourceType:"module",locations:!0,onComment:n})}catch(e){return console.warn(`Parse error in ${t}:`,e.message),s}const o=buildJSDocTypeMap(n,e),a=new Set;l.simple(r,{ImportDeclaration(e){for(const t of e.specifiers)"ImportDefaultSpecifier"===t.type?s.imports.push(t.local.name):"ImportSpecifier"===t.type&&s.imports.push(t.imported.name)},ExportNamedDeclaration(e){if(e.declaration)if(e.declaration.id)a.add(e.declaration.id.name);else if(e.declaration.declarations)for(const t of e.declaration.declarations)a.add(t.id.name);if(e.specifiers)for(const t of e.specifiers)a.add(t.exported.name)},ExportDefaultDeclaration(e){e.declaration&&e.declaration.id&&a.add(e.declaration.id.name)},ClassDeclaration(e){const n={name:e.id.name,extends:e.superClass?e.superClass.name:null,methods:[],properties:[],calls:[],dbReads:[],dbWrites:[],file:t,line:e.loc.start.line};for(const t of e.body.body)if("MethodDefinition"===t.type&&"constructor"!==t.key.name)n.methods.push(t.key.name),extractCallsAndSQL(t.value.body,n.calls,n.dbReads,n.dbWrites);else if("PropertyDefinition"===t.type&&"init$"===t.key.name&&t.value&&"ObjectExpression"===t.value.type)for(const e of t.value.properties)e.key&&e.key.name&&n.properties.push(e.key.name);s.classes.push(n)},FunctionDeclaration(e){if(e.id){const n=e.params.map(e=>"Identifier"===e.type?e.name:"AssignmentPattern"===e.type&&"Identifier"===e.left.type?e.left.name+"=":"RestElement"===e.type&&"Identifier"===e.argument.type?"..."+e.argument.name:"ObjectPattern"===e.type?"options":"?"),r=findJSDocForNode(o,e.loc.start.line),a=enrichParamsWithTypes(n,r),i={name:e.id.name,exported:!1,params:a,async:e.async||!1,returns:r?.returns||null,calls:[],dbReads:[],dbWrites:[],file:t,line:e.loc.start.line};extractCallsAndSQL(e.body,i.calls,i.dbReads,i.dbWrites),s.functions.push(i)}}});for(const e of s.functions)e.exported=a.has(e.name);return s.exports=[...a],s}const S=new Set(["query","execute","raw","exec","queryFile","none","one","many","any","oneOrNone","manyOrNone","result"]);function extractCallsAndSQL(e,t,s,n){e&&l.simple(e,{CallExpression(e){const r=e.callee;if("MemberExpression"===r.type){const e=r.object,s=r.property;if("Identifier"===s.type)if("Identifier"===e.type){const n=`${e.name}.${s.name}`;t.includes(n)||t.push(n)}else if("MemberExpression"===e.type&&"Identifier"===e.property.type){const n=`${e.property.name}.${s.name}`;t.includes(n)||t.push(n)}else if("ThisExpression"===e.type){const e=s.name;t.includes(e)||t.push(e)}}else if("Identifier"===r.type){const e=r.name;t.includes(e)||t.push(e)}if(s&&n){const t=getCallMethodName(e);if(t&&S.has(t)&&e.arguments.length>0){const t=extractStringValue(e.arguments[0]);if(t&&g(t)){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}}}},TaggedTemplateExpression(e){if(!s||!n)return;
const t=getTagName(e.tag);if(t&&/sql/i.test(t)){const t=templateToString(e.quasi);if(t){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}}},TemplateLiteral(e){if(!s||!n)return;
const t=templateToString(e);if(t&&g(t)){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}},Literal(e){if(s&&n&&"string"==typeof e.value&&g(e.value)){const t=y(e.value);t.reads.forEach(e=>{s.includes(e)||s.push(e)}),t.writes.forEach(e=>{n.includes(e)||n.push(e)})}}})}
function getTagName(e){return"Identifier"===e.type?e.name:"MemberExpression"===e.type&&"Identifier"===e.property.type?e.property.name:null}
function getCallMethodName(e){const t=e.callee;return"MemberExpression"===t.type&&"Identifier"===t.property.type?t.property.name:null}
function extractStringValue(e){return e?"Literal"===e.type&&"string"==typeof e.value?e.value:"TemplateLiteral"===e.type?templateToString(e):null:null}
function templateToString(e){if(!e||!e.quasis)return"";
let t="";for(let s=0;s<e.quasis.length;s++)t+=e.quasis[s].value.cooked||e.quasis[s].value.raw||"",s<e.expressions?.length&&(t+="$"+(s+1));return t}
export function discoverSubProjects(i){const l=a(i),c=[],p=["packages","apps","services","modules","libs","plugins"];for(const a of p){const i=r(l,a);if(n(i))try{for(const a of t(i)){const t=r(i,a),p=r(t,"package.json");if(s(t).isDirectory()&&n(p))try{const s=JSON.parse(e(p,"utf-8"));c.push({name:s.name||a,path:o(l,t),absolutePath:t})}catch{c.push({name:a,path:o(l,t),absolutePath:t})}}}catch{}}return c}
export async function parseProject(t,s={}){const n={files:[],classes:[],functions:[],imports:[],exports:[],tables:[]},i=a(t),l=findJSFiles(t);for(const t of l)try{const s=e(t,"utf-8"),r=o(i,t),a=await parseFileByExtension(s,r);n.files.push(r),n.classes.push(...a.classes),n.functions.push(...a.functions),n.imports.push(...a.imports),n.exports.push(...a.exports),a.tables?.length&&n.tables.push(...a.tables)}catch(e){}if(s.recursive){const e=discoverSubProjects(t);n.subProjects=[];for(const t of e)try{const e=await parseProject(t.absolutePath);for(const s of e.files)n.files.push(r(t.path,s));for(const s of e.classes)s.file=r(t.path,s.file),n.classes.push(s);for(const s of e.functions)s.file=r(t.path,s.file),n.functions.push(s);n.imports.push(...e.imports),n.exports.push(...e.exports),e.tables?.length&&n.tables.push(...e.tables),n.subProjects.push({name:t.name,path:t.path,files:e.files.length})}catch{}}return n.imports=[...new Set(n.imports)],n.exports=[...new Set(n.exports)],n}
async function parseFileByExtension(e,t){return t.endsWith(".sql")?h(e,t):t.endsWith(".py")?d(e,t):t.endsWith(".go")?m(e,t):t.endsWith(".ts")||t.endsWith(".tsx")?f(e,t):parseFile(e,t)}
function isSourceFile(e){return!e.endsWith(".css.js")&&!e.endsWith(".tpl.js")&&x.some(t=>e.endsWith(t))}
export function findJSFiles(e,n=e){e===n&&u(n);
const a=[];try{for(const i of t(e)){const t=r(e,i),l=s(t),u=o(n,e);l.isDirectory()?c(i,u)||a.push(...findJSFiles(t,n)):isSourceFile(i)&&(p(i,u)||a.push(t))}}catch(t){console.warn(`Cannot read directory ${e}:`,t.message)}return a}
export function findAllProjectFiles(e,n=e){e===n&&u(n);
const i=[],l=a(n);try{for(const a of t(e)){const t=r(e,a),u=s(t),f=o(l,e);u.isDirectory()?c(a,f)||i.push(...findAllProjectFiles(t,n)):p(a,f)||i.push(o(l,t))}}catch(t){console.warn(`Cannot read directory ${e}:`,t.message)}return i}
function buildJSDocTypeMap(e,t){const s=new Map;for(const n of e){if("Block"!==n.type||!n.value.startsWith("*"))continue;
const e="/*"+n.value+"*/",r=t.slice(0,n.end).split("\n").length,o=[],a=/@param\s+\{/g;
let i;for(;null!==(i=a.exec(e));){let t=1,s=i.index+i[0].length;for(;s<e.length&&t>0;)"{"===e[s]?t++:"}"===e[s]&&t--,s++;if(0!==t)continue;
const n=e.slice(i.index+i[0].length,s-1),r=e.slice(s).match(/^\s+(\[?\w+(?:\.\w+)*\]?)/);if(!r)continue;
let a=r[1];a.startsWith("[")&&(a=a.slice(1)),a.endsWith("]")&&(a=a.slice(0,-1)),a.includes(".")||o.push({name:a,type:n})}let l=null;
const c=e.match(/@returns?\s+\{([^}]+)\}/);c&&(l=c[1]),(o.length>0||l)&&s.set(r,{params:o,returns:l})}return s}
function findJSDocForNode(e,t){for(let s=1;s<=3;s++){const n=e.get(t-s);if(n)return n}return null}
function enrichParamsWithTypes(e,t){if(!t||0===t.params.length)return e;
const s=new Map;for(const e of t.params)s.set(e.name,e.type);return e.map(e=>{const t=e.startsWith("..."),n=e.endsWith("=");
let r=e;t&&(r=r.slice(3)),n&&(r=r.slice(0,-1));
let o=s.get(r);return o?(o.startsWith("...")&&(o=o.slice(3)),`${t?"...":""}${r}:${o}${n?"=":""}`):e})}