// @ctx .context/src/analysis/jsdoc-checker.ctx
import{readFileSync as e,readdirSync as t,statSync as n}from"fs";import{join as s,relative as r,resolve as i}from"path";import{parse as o}from"../../vendor/acorn.mjs";
import*as a from"../../vendor/walk.mjs";
import{shouldExcludeDir as c,shouldExcludeFile as l,parseGitignore as u}from"../core/filters.js";
function f(e,i=e){e===i&&u(i);const o=[];try{for(const a of t(e)){const t=s(e,a),u=r(i,t);n(t).isDirectory()?c(a,u)||o.push(...f(t,i)):!a.endsWith(".js")||a.endsWith(".css.js")||a.endsWith(".tpl.js")||l(a,u)||o.push(t)}}catch(e){}return o}
function m(e,t){for(const n of e){const e=t-n.endLine;if(e>=0&&e<=2)return n}return null}
function p(e){return"Identifier"===e.type?e.name:"AssignmentPattern"===e.type&&"Identifier"===e.left.type?e.left.name:"RestElement"===e.type&&"Identifier"===e.argument.type?e.argument.name:"ObjectPattern"===e.type?"options":"ArrayPattern"===e.type?"args":"param"}
function h(e){if("AssignmentPattern"!==e.type)return null;const t=e.right;if("Literal"===t.type){if("string"==typeof t.value)return"string";if("number"==typeof t.value)return"number";if("boolean"==typeof t.value)return"boolean"}return"ArrayExpression"===t.type?"Array":"ObjectExpression"===t.type?"Object":null}
function y(e){let t=!1;try{a.simple(e.body,{ReturnStatement(e){e.argument&&(t=!0)},FunctionDeclaration(){},FunctionExpression(){},ArrowFunctionExpression(){}})}catch(e){}return t}
function d(e,t,n,s,r,i){const o=[];if(!e)return o;const a=e.params;a.length>0&&a.length!==t.length&&o.push({file:r,line:i,name:s,severity:"error",message:`Param count mismatch: JSDoc has ${a.length}, function has ${t.length}`});const c=Math.min(a.length,t.length);for(let e=0;e<c;e++){const n=a[e].name,c=p(t[e]);n!==c&&"options"!==c&&"args"!==c&&"param"!==c&&o.push({file:r,line:i,name:s,severity:"error",message:`Param name mismatch at position ${e}: JSDoc says "${n}", code has "${c}"`})}!e.hasReturns&&y(n)&&o.push({file:r,line:i,name:s,severity:"warning",message:"Function returns a value but JSDoc has no @returns"});for(let e=0;e<c;e++){const n=a[e].type,c=h(t[e]);if(c&&n&&"*"!==n){let t=n.toLowerCase().includes(c.toLowerCase());!t&&"string"===c&&n.includes("'")&&n.includes("|")&&(t=!0),!t&&"Array"===c&&n.includes("[]")&&(t=!0),t||o.push({file:r,line:i,name:s,severity:"warning",message:`Type mismatch for "${a[e].name}": JSDoc says {${n}}, default value suggests {${c}}`})}}return o}
export function checkJSDocFile(e,t){const n=[];let s;try{s=o(e,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(e){return n}const r=function(e){const t=[],n=/\/\*\*[\s\S]*?\*\//g;let s;for(;null!==(s=n.exec(e));){const n=s[0],r=e.slice(0,s.index+n.length).split("\n").length,i=[],o=/@param\s+\{/g;let a;for(;null!==(a=o.exec(n));){let e=1,t=a.index+a[0].length;for(;t<n.length&&e>0;)"{"===n[t]?e++:"}"===n[t]&&e--,t++;if(0!==e)continue;const s=n.slice(a.index+a[0].length,t-1),r=n.slice(t).match(/^\s+(\[?\w+(?:\.\w+)*\]?)/);if(!r)continue;let o=r[1];o.startsWith("[")&&(o=o.slice(1)),o.endsWith("]")&&(o=o.slice(0,-1)),o.includes(".")||i.push({name:o,type:s})}const c=/@returns?\s/.test(n);t.push({text:n,endLine:r,params:i,hasReturns:c})}return t}(e);return a.simple(s,{FunctionDeclaration(e){if(!e.id)return;const s=m(r,e.loc.start.line);s&&n.push(...d(s,e.params,e,e.id.name,t,e.loc.start.line))},VariableDeclaration(e){for(const s of e.declarations){if(!s.init)continue;const i="ArrowFunctionExpression"===s.init.type||"FunctionExpression"===s.init.type?s.init:null;if(!i||!s.id?.name)continue;const o=m(r,e.loc.start.line);o&&n.push(...d(o,i.params,i,s.id.name,t,e.loc.start.line))}},ClassDeclaration(e){const s=e.id?.name||"Anonymous";for(const i of e.body.body){if("MethodDefinition"!==i.type)continue;const e=i.key.name||i.key.value;if(!e||"constructor"===e)continue;if("method"!==i.kind)continue;const o=i.value,a=m(r,i.loc.start.line);a&&n.push(...d(a,o.params,o,`${s}.${e}`,t,i.loc.start.line))}}}),n}
export function checkJSDocConsistency(t){const n=i(t),s=f(t),o=[];for(const t of s){let s;try{s=e(t,"utf-8")}catch(e){continue}const i=checkJSDocFile(s,r(n,t));o.push(...i)}const a=o.filter(e=>"error"===e.severity).length,c=o.filter(e=>"warning"===e.severity).length,l={};for(const e of o)l[e.file]=(l[e.file]||0)+1;return{issues:o,summary:{total:o.length,errors:a,warnings:c,byFile:l}}}