import{readFileSync as t,readdirSync as e,statSync as i}from"fs";import{join as n,relative as o,resolve as r}from"path";import{parse as l}from"../vendor/acorn.mjs";import*as a from"../vendor/walk.mjs";import{shouldExcludeDir as c,shouldExcludeFile as s,parseGitignore as m}from"./filters.js";function findJSFiles(t,r=t){t===r&&m(r);
const l=[];try{for(const a of e(t)){const e=n(t,a),m=o(r,e);i(e).isDirectory()?c(a,m)||l.push(...findJSFiles(e,r)):!a.endsWith(".js")||a.endsWith(".css.js")||a.endsWith(".tpl.js")||s(a,m)||l.push(e)}}catch(t){}return l}
function calculateComplexity(t){let e=1;return a.simple(t,{IfStatement(){e++},ConditionalExpression(){e++},ForStatement(){e++},ForOfStatement(){e++},ForInStatement(){e++},WhileStatement(){e++},DoWhileStatement(){e++},SwitchCase(t){t.test&&e++},LogicalExpression(t){"&&"!==t.operator&&"||"!==t.operator||e++},BinaryExpression(t){"??"===t.operator&&e++},CatchClause(){e++}}),e}
function getRating(t){return t<=5?"low":t<=10?"moderate":t<=20?"high":"critical"}
export function analyzeComplexityFile(t,e){const i=[];
let n;try{n=l(t,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(t){return i}return a.simple(n,{FunctionDeclaration(t){if(!t.id)return;
const n=calculateComplexity(t.body);i.push({name:t.id.name,type:"function",file:e,line:t.loc.start.line,complexity:n,rating:getRating(n)})},ArrowFunctionExpression(t){if("BlockStatement"!==t.body.type)return;
const n=calculateComplexity(t.body);n>5&&i.push({name:"(arrow)",type:"function",file:e,line:t.loc.start.line,complexity:n,rating:getRating(n)})},MethodDefinition(t){if("method"!==t.kind)return;
const n=t.key.name||t.key.value,o=calculateComplexity(t.value.body);i.push({name:n,type:"method",file:e,line:t.loc.start.line,complexity:o,rating:getRating(o)})}}),i}
function analyzeFile(e,i){let n;try{n=t(e,"utf-8")}catch(t){return[]}return analyzeComplexityFile(n,o(i,e))}
export async function getComplexity(t,e={}){const i=e.minComplexity||1,n=e.onlyProblematic||!1,o=r(t),l=findJSFiles(t);
let a=[];for(const t of l)a.push(...analyzeFile(t,o));a=a.filter(t=>!(t.complexity<i)&&(!n||"low"!==t.rating&&"moderate"!==t.rating)),a.sort((t,e)=>e.complexity-t.complexity);
const c={low:a.filter(t=>"low"===t.rating).length,moderate:a.filter(t=>"moderate"===t.rating).length,high:a.filter(t=>"high"===t.rating).length,critical:a.filter(t=>"critical"===t.rating).length,average:a.length>0?Math.round(a.reduce((t,e)=>t+e.complexity,0)/a.length*10)/10:0};return{total:a.length,stats:c,items:a.slice(0,30)}}