import{readFileSync as e,readdirSync as t,statSync as n,existsSync as o}from"fs";import{join as i,relative as s,resolve as a,dirname as r}from"path";import{parse as c}from"../vendor/acorn.mjs";import*as l from"../vendor/walk.mjs";import{shouldExcludeDir as d,shouldExcludeFile as f,parseGitignore as p}from"./filters.js";function findJSFiles(e,o=e){e===o&&p(o);
const a=[];try{for(const r of t(e)){const t=i(e,r),c=s(o,t);n(t).isDirectory()?d(r,c)||a.push(...findJSFiles(t,o)):!r.endsWith(".js")||r.endsWith(".css.js")||r.endsWith(".tpl.js")?(r.endsWith(".css.js")||r.endsWith(".tpl.js"))&&(f(r,c)||a.push(t)):f(r,c)||a.push(t)}}catch(e){}return a}
function findProjectRoot(e){let t=a(e);for(;t!==r(t);){if(o(i(t,"package.json")))return t;t=r(t)}return a(e)}
function analyzeFile(e){const t=new Set,n=new Set,o=new Set,i=[],s=[];
let a;try{a=c(e,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(e){return{definitions:t,calls:n,exports:o,imports:i,namedExports:s}}return l.simple(a,{FunctionDeclaration(e){e.id&&t.add(e.id.name)},ClassDeclaration(e){e.id&&t.add(e.id.name)},CallExpression(e){"Identifier"===e.callee.type?n.add(e.callee.name):"MemberExpression"===e.callee.type&&"Identifier"===e.callee.object.type&&n.add(e.callee.object.name);for(const t of e.arguments)"Identifier"===t.type&&n.add(t.name)},NewExpression(e){"Identifier"===e.callee.type&&n.add(e.callee.name)},ImportDeclaration(e){const t=e.source.value;for(const n of e.specifiers)"ImportSpecifier"===n.type?i.push({name:n.imported.name,source:t}):"ImportDefaultSpecifier"===n.type&&i.push({name:"default",source:t})},ExportNamedDeclaration(e){if(e.declaration)if(e.declaration.id){const t=e.declaration.id.name;o.add(t),s.push({name:t,line:e.loc.start.line})}else if(e.declaration.declarations)for(const t of e.declaration.declarations)if("Identifier"===t.id.type){const n=t.id.name;o.add(n),s.push({name:n,line:e.loc.start.line})}if(e.specifiers)for(const t of e.specifiers){const n=t.exported.name;o.add(n),s.push({name:n,line:e.loc.start.line})}},ExportDefaultDeclaration(e){e.declaration?.id&&o.add(e.declaration.id.name)}}),{definitions:t,calls:n,exports:o,imports:i,namedExports:s}}
function analyzeFileLocals(e){const t=[],n=[];
let o;try{o=c(e,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(e){return{unusedVars:t,unusedImports:n}}const i=new Set,s=[],a=[],r=new Set;l.simple(o,{VariableDeclaration(e){const t="ExportNamedDeclaration"===e.parent?.type;for(const n of e.declarations)"Identifier"===n.id.type&&(s.push({name:n.id.name,line:n.loc.start.line,isExported:t}),r.add(n.id))},ImportDeclaration(e){for(const t of e.specifiers){const n=t.local.name,o="ImportSpecifier"===t.type?t.imported.name:"ImportDefaultSpecifier"===t.type?"default":"*";a.push({name:o,local:n,source:e.source.value,line:e.loc.start.line}),r.add(t.local)}}});
const d=new Set;for(const e of o.body){if("ExportNamedDeclaration"===e.type&&e.declaration){if(e.declaration.declarations)for(const t of e.declaration.declarations)"Identifier"===t.id.type&&d.add(t.id.name);e.declaration.id&&d.add(e.declaration.id.name)}if("ExportNamedDeclaration"===e.type&&e.specifiers)for(const t of e.specifiers)d.add(t.local.name)}l.simple(o,{Identifier(e){i.add(e.name)}});for(const n of s){if(d.has(n.name))continue;if(n.name.startsWith("_"))continue;
const o=new RegExp(`\\b${n.name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"g"),i=e.match(o);i&&i.length<=1&&t.push({name:n.name,line:n.line})}for(const t of a){if("*"===t.name)continue;
const o=new RegExp(`\\b${t.local.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"g"),i=e.match(o);i&&i.length<=1&&n.push(t)}return{unusedVars:t,unusedImports:n}}
export async function getDeadCode(t){const n=a(t),o=findJSFiles(t),i=[],d=new Set,f=new Set,p=[],m=new Map,u=findJSFiles(findProjectRoot(t));for(const t of u){let o;try{o=e(t,"utf-8")}catch{continue}const i=s(n,t),{imports:c}=analyzeFile(o);for(const e of c){if(!e.source.startsWith("."))continue;
const o=r(t);
let c=a(o,e.source);c.endsWith(".js")||(c+=".js");
const l=s(n,c),d=`${e.name}@${l}`;m.has(d)||m.set(d,new Set),m.get(d).add(i)}}for(const t of o){const o=e(t,"utf-8"),i=s(n,t),{definitions:a,calls:r,exports:c,namedExports:l}=analyzeFile(o);for(const e of r)d.add(e);for(const e of c)f.add(e);p.push({file:i,code:o,definitions:a,calls:r,exports:c,namedExports:l})}for(const{file:e,code:t,definitions:n,exports:o}of p){if(e.includes(".test.")||e.includes("/tests/"))continue;if(e.endsWith(".css.js")||e.endsWith(".tpl.js"))continue;
let n;try{n=c(t,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(e){continue}l.simple(n,{FunctionDeclaration(t){if(!t.id)return;
const n=t.id.name;o.has(n)||f.has(n)||d.has(n)||n.startsWith("_")||i.push({name:n,type:"function",file:e,line:t.loc.start.line,reason:"Never called"})},ClassDeclaration(t){if(!t.id)return;
const n=t.id.name;o.has(n)||f.has(n)||d.has(n)||i.push({name:n,type:"class",file:e,line:t.loc.start.line,reason:"Never instantiated"})}})}for(const{file:e,calls:t,namedExports:n}of p)if(!e.includes(".test.")&&!e.includes("/tests/"))for(const o of n){if(t.has(o.name))continue;
const n=`${o.name}@${e}`,s=m.get(n);s&&0!==s.size||i.push({name:o.name,type:"export",file:e,line:o.line,reason:"Exported but never imported"})}for(const{file:e,code:t}of p){if(e.includes(".test.")||e.includes("/tests/"))continue;if(e.endsWith(".css.js")||e.endsWith(".tpl.js"))continue;const{unusedVars:n,unusedImports:o}=analyzeFileLocals(t);for(const t of n)i.push({name:t.name,type:"variable",file:e,line:t.line,reason:"Declared but never used"});for(const t of o)i.push({name:t.local,type:"import",file:e,line:t.line,reason:`Imported from '${t.source}' but never used`})}const h={function:i.filter(e=>"function"===e.type).length,class:i.filter(e=>"class"===e.type).length,export:i.filter(e=>"export"===e.type).length,variable:i.filter(e=>"variable"===e.type).length,import:i.filter(e=>"import"===e.type).length};return{total:i.length,byType:h,items:i.slice(0,50)}}