// @ctx .context/src/decompile.ctx
import{readFileSync as e,writeFileSync as t,mkdirSync as n,existsSync as o,readdirSync as s,statSync as r}from"fs";import{join as i,basename as a,extname as c,dirname as l,relative as p}from"path";import{minify as u}from"../vendor/terser.mjs";import{parse as m}from"../vendor/acorn.mjs";import{simple as d}from"../vendor/walk.mjs";function parseCtxSignatures(e){const t=new Map;if(!e)return t;for(const n of e.split("\n")){const e=n.trim();if(!e||e.startsWith("---")||e.startsWith("@")||e.startsWith("CALLS")||e.startsWith("R→")||e.startsWith("W→")||e.startsWith("PATTERNS:")||e.startsWith("EDGE_CASES:")||e.startsWith("Rules:")||e.startsWith("Save this"))continue;
const o=e.match(/^class\s+([\w]+)([^|]*)\|([^|]*)\|?(.*)$/);if(o){t.set(o[1],{type:"class",extends:o[2].replace(/\s*extends\s*/,"").trim()||null,meta:o[3].trim(),description:o[4]?.trim()||"",exported:!1});continue}const s=e.match(/^\s+\.(\w+)\(([^)]*)\)\|?(.*)$/);if(s){t.set(s[1],{type:"method",params:parseCtxParams(s[2]),description:s[3]?.trim()||""});continue}const r=e.match(/^(export\s+)?(\w+)\(([^)]*)\)(→[^|]*)?\|(.*)$/);if(r){const e=r[2],n=r[3],o=r[4]||"",s=(r[5]||"").split("|"),i=s[0]?.trim()||"";t.set(e,{type:"function",params:parseCtxParams(n),returnType:extractReturnType(o),description:i,exported:!!r[1]});continue}}return t}
function parseCtxParams(e){return e&&e.trim()?e.split(",").map(e=>{const t=e.trim();if(!t)return null;
const n=t.match(/^(\w+)(\?)?(?::(\w[\w<>\[\]|.]*))?(=)?$/);if(n)return{name:n[1],type:n[3]||null,optional:!(!n[2]&&!n[4])};
const o=t.match(/^(\w+)(=)?$/);return o?{name:o[1],type:null,optional:!!o[2]}:"..."===t?{name:"args",type:null,rest:!0}:{name:t.replace(/[=?:].*/g,""),type:null}}).filter(Boolean):[]}
function extractReturnType(e){if(!e)return null;
const t=e.match(/^→([A-Z][\w<>\[\]|]*)/);return t?t[1]:null}
function sanitizeJSDocText(e){return e.replace(/\*\//g,"*\\/")}
function generateJSDoc(e){const t=["/**"];if(e.description&&"{DESCRIBE}"!==e.description&&t.push(` * ${sanitizeJSDocText(e.description)}`),e.params&&e.params.length>0)for(const n of e.params){const e=n.type||"*",o=n.optional?`[${n.name}]`:n.name;t.push(` * @param {${e}} ${o}`)}return e.returnType&&t.push(` * @returns {${e.returnType}}`),t.push(" */"),t.join("\n")}
export async function decompileFile(t,n,o={}){const{indentLevel:s=2}=o,r=e(t,"utf-8");if(!r.trim())return{code:"",injected:0,original:0,decompiled:0};
let i;try{i=(await u(r,{compress:!1,mangle:!1,module:!0,output:{beautify:!0,comments:!1,indent_level:s,semicolons:!0}})).code||r}catch{i=r}const a=parseCtxSignatures(n);if(0===a.size)return{code:i,injected:0,original:r.length,decompiled:i.length};
let c;try{c=m(i,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch{return{code:i,injected:0,original:r.length,decompiled:i.length}}const l=[];d(c,{ExportNamedDeclaration(e){const t=e.declaration;if(t){if("FunctionDeclaration"===t.type&&t.id?.name){const n=a.get(t.id.name);n&&l.push({pos:e.start,jsdoc:generateJSDoc(n)})}if("ClassDeclaration"===t.type&&t.id?.name){const n=a.get(t.id.name);n&&n.description&&l.push({pos:e.start,jsdoc:`/**\n * ${n.description}\n */`})}}},FunctionDeclaration(e){if(!e.id?.name)return;
const t=a.get(e.id.name);t&&!t.exported&&l.push({pos:e.start,jsdoc:generateJSDoc(t)})},ClassDeclaration(e){if(!e.id?.name)return;
const t=a.get(e.id.name);t&&!t.exported&&t.description&&l.push({pos:e.start,jsdoc:`/**\n * ${t.description}\n */`})}}),l.sort((e,t)=>t.pos-e.pos);
let p=i,f=0;for(const{pos:e,jsdoc:t}of l){const n=p.lastIndexOf("\n",e-1),o=-1===n?0:n+1,s=p.slice(o,e).match(/^(\s*)/)?.[1]||"",r=t.split("\n").map(e=>s+e).join("\n");p=p.slice(0,e)+r+"\n"+p.slice(e),f++}try{const e=m(p,{ecmaVersion:"latest",sourceType:"module",locations:!0});p=function(e,t,n){const o=[],s=new Set,visitor=t=>{const r=t.declaration||t;if("FunctionDeclaration"!==r.type||!r.id?.name)return;if(s.has(r.id.name))return;s.add(r.id.name);
const i=n.get(r.id.name);if(!i||!i.params||0===i.params.length)return;
const a=r.params.map(e=>"Identifier"===e.type?e.name:"AssignmentPattern"===e.type&&"Identifier"===e.left.type?e.left.name:null).filter(Boolean),c=[];for(let e=0;e<Math.min(a.length,i.params.length);e++)a[e]!==i.params[e].name&&c.push(a[e]+"="+i.params[e].name);if(0===c.length)return;
const l=e.indexOf(")",r.params[r.params.length-1].end);l>-1&&o.push({pos:l+1,text:" /* "+c.join(", ")+" */"})};d(t,{FunctionDeclaration:visitor,ExportNamedDeclaration(e){e.declaration&&"FunctionDeclaration"===e.declaration.type&&visitor(e)}}),o.sort((e,t)=>t.pos-e.pos);
let r=e;for(const e of o)r=r.slice(0,e.pos)+e.text+r.slice(e.pos);return r}(p,e,a);
const t=function(e){const t=[];if(d(e,{ImportDeclaration(e){for(const n of e.specifiers)"ImportSpecifier"===n.type&&n.imported.name!==n.local.name?t.push({original:n.imported.name,alias:n.local.name,source:e.source.value}):"ImportDefaultSpecifier"===n.type?t.push({original:"default",alias:n.local.name,source:e.source.value}):"ImportNamespaceSpecifier"===n.type&&n.local.name.length<=2&&t.push({original:"*",alias:n.local.name,source:e.source.value})}}),0===t.length)return"";
const n=new Map;for(const e of t){const t=e.source.split("/").pop().replace(/\.\w+$/,"");n.has(t)||n.set(t,[]),n.get(t).push(e.alias+"="+("*"===e.original?"* (namespace)":e.original))}const o=[];for(const[e,t]of n)o.push(` * ${e}: ${t.join(", ")}`);return"/**\n * @names Import aliases\n"+o.join("\n")+"\n */\n"}(e);t&&(p=t+p)}catch{}return{code:p,injected:f,original:r.length,decompiled:p.length}}const f=new Set(["node_modules",".git","vendor",".context","dev-docs",".agent",".agents",".full","web"]),h=new Set([".js",".mjs"]);function walkJSFiles(e,t=e){const n=[];try{for(const o of s(e)){if(o.startsWith(".")&&"."!==o)continue;
const s=i(e,o);r(s).isDirectory()?f.has(o)||n.push(...walkJSFiles(s,t)):h.has(c(o).toLowerCase())&&n.push(s)}}catch{}return n}
function resolveCtx(t,n){const s=a(n,c(n))+".ctx",r=l(n),p=i(t,r,s);if(o(p))return e(p,"utf-8");
const u=i(t,".context",r,s);return o(u)?e(u,"utf-8"):null}
export async function decompileProject(e,s={}){const{dryRun:r=!1,outputDir:a}=s,c=a||i(e,".full"),u=i(e,"src");if(!o(u))return{error:"No src/ directory found",files:0};
const m=walkJSFiles(u,e),d=[],f=[];
let h=0;for(const s of m){const a=p(e,s);try{const p=resolveCtx(e,a),u=await decompileFile(s,p);if(!r){const e=i(c,a),s=l(e);o(s)||n(s,{recursive:!0}),t(e,u.code,"utf-8")}d.push({file:a,injected:u.injected,original:u.original,decompiled:u.decompiled}),h+=u.injected}catch(e){f.push({file:a,error:e.message})}}return{outputDir:c,files:d.length,totalJSDocInjected:h,fileDetails:d,errors:f.length>0?f:void 0,dryRun:r}}
function extractDeclarations(e){const t=[];try{const n=m(e,{ecmaVersion:"latest",sourceType:"module",locations:!0});d(n,{FunctionDeclaration(e){t.push({name:e.id?.name||"<anonymous>",line:e.loc.start.line,endLine:e.loc.end.line,type:"function"})},ClassDeclaration(e){t.push({name:e.id?.name||"<anonymous>",line:e.loc.start.line,endLine:e.loc.end.line,type:"class"})},VariableDeclaration(e){for(const n of e.declarations)!n.init||"ArrowFunctionExpression"!==n.init.type&&"FunctionExpression"!==n.init.type||t.push({name:n.id?.name||"<anonymous>",line:e.loc.start.line,endLine:e.loc.end.line,type:"function"})}})}catch{}return t}
export function buildLineMap(e,t){const n=extractDeclarations(e),o=extractDeclarations(t),s=new Map,r=new Map;for(const e of n)r.set(e.name,e);for(const e of o){const t=r.get(e.name);if(t)for(let n=e.line;n<=e.endLine;n++)s.set(n,{compactLine:t.line,symbol:e.name,type:e.type})}return s}
export function mapFullToCompact(t,n,o){try{return buildLineMap(e(t,"utf-8"),e(n,"utf-8")).get(o)||null}catch{return null}}