import{readFileSync as t,readdirSync as e,existsSync as s,mkdirSync as n,writeFileSync as o,statSync as c}from"fs";import{join as r,basename as i,extname as a,dirname as l,relative as h}from"path";import{execSync as f}from"child_process";import{createHash as u}from"crypto";import{writeCache as p,computeContentHash as m}from"./analysis-cache.js";import{analyzeComplexityFile as d}from"./complexity.js";import{checkUndocumentedFile as $}from"./undocumented.js";import{checkJSDocFile as x}from"./jsdoc-checker.js";
export function generateDocDialect(t,e){const s=[],n=e?i(e):"unknown";s.push(`=== PROJECT: ${n} ===`);const{stats:o}=t,c=[];o.files>0&&c.push(`${o.files} files`),o.classes>0&&c.push(`${o.classes} classes`),o.functions>0&&c.push(`${o.functions} functions`),o.tables>0&&c.push(`${o.tables} tables`),s.push(`STATS: ${c.join("|")}`);
const r=t.edges.filter(t=>"→"===t[1]).length,a=t.edges.filter(t=>"R→"===t[1]).length,l=t.edges.filter(t=>"W→"===t[1]).length,h=[];r>0&&h.push(`${r} calls`),a>0&&h.push(`${a} db_reads`),l>0&&h.push(`${l} db_writes`),h.length>0&&s.push(`EDGES: ${h.join("|")}`),t.orphans.length>0&&s.push(`ORPHANS: ${t.orphans.join(",")}`),Object.keys(t.duplicates).length>0&&s.push(`DUPLICATES: ${Object.keys(t.duplicates).join(",")}`);
const f={};for(const[e,s]of Object.entries(t.nodes)){const t=s.f||"?";f[t]||(f[t]=[]),f[t].push({shortName:e,...s})}for(const[e,n]of Object.entries(f)){if("?"===e)continue;s.push(""),s.push(`--- ${e} ---`);for(const e of n){const n=t.reverseLegend[e.shortName]||e.shortName;if("C"===e.t){const o=e.x?` extends ${e.x}`:"",c=e.m?.length||0,r=e.$?.length||0,i=[];if(c>0&&i.push(`${c}m`),r>0&&i.push(`${r}$`),s.push(`class ${n}${o}|${i.join(",")}`),e.m)for(const n of e.m){const e=t.reverseLegend[n]||n;s.push(`  .${e}`)}}else if("F"===e.t){const t=e.e?"export ":"";s.push(`${t}${n}()`)}else if("T"===e.t){const t=e.cols?.join(",")||"";s.push(`TABLE ${n}|${t}`)}}const o=t.edges.filter(s=>{const n=t.nodes[s[0]];return n?.f===e});if(o.length>0){const e=o.map(e=>{const s=t.reverseLegend[e[0]]||e[0],n=t.reverseLegend[e[2]?.split(".")[0]]||e[2];return`${s}${e[1]}${n}`}),n=[...new Set(e)];n.length<=5?s.push(`CALLS: ${n.join("|")}`):s.push(`CALLS: ${n.slice(0,5).join("|")}|+${n.length-5} more`)}}return s.join("\n")}
function walkCtxFiles(t,n){const o=[];if(!s(t))return o;try{for(const s of e(t)){const e=r(t,s);try{c(e).isDirectory()?o.push(...walkCtxFiles(e,n)):(s.endsWith(".ctx")||s.endsWith(".ctx.md"))&&o.push({relPath:h(n,e),absPath:e})}catch{}}}catch{}return o}
function resolveCtxPath(t,e){const n=i(e,a(e))+".ctx",o=l(e),c=r(t,o,n);if(s(c))return c;
const h=r(t,".context",o,n);return s(h)?h:null}
function resolveCtxMdPath(t,e){const n=i(e,a(e))+".ctx.md",o=l(e),c=r(t,o,n);if(s(c))return c;
const h=r(t,".context",o,n);return s(h)?h:null}
export function readContextDocs(e){const s=r(e,".context"),n=new Map;for(const{relPath:e,absPath:o}of walkCtxFiles(s,s))try{const s=t(o,"utf-8").trim();s&&n.set(e,s)}catch{}const o=walkCtxFiles(e,e).filter(t=>!t.relPath.startsWith(".context"));for(const{relPath:e,absPath:s}of o)try{const o=t(s,"utf-8").trim();o&&n.set(e,o)}catch{}const c=[...n.keys()].sort((t,e)=>"project.ctx"===t?-1:"project.ctx"===e?1:i(t).startsWith("_")?-1:i(e).startsWith("_")?1:t.localeCompare(e)),a=c,l=c.map(t=>n.get(t)),h=n.has("project.ctx");return{combined:l.join("\n\n"),files:a,hasProjectCtx:h}}
export function getProjectDocs(e,s,n={}){const{file:o}=n,c=readContextDocs(s);if(o){const n=resolveCtxPath(s,o);
let c="";if(n)c=t(n,"utf-8").trim();else{const t=generateDocDialect(e,s),n=`--- ${o} ---`,r=t.indexOf(n);if(-1===r)return`No documentation found for: ${o}`;
const i=t.indexOf("\n---",r+n.length);c=-1===i?t.slice(r).trim():t.slice(r,i).trim()}const r=resolveCtxMdPath(s,o);if(r){const e=t(r,"utf-8").trim();e&&!e.match(/^#[^\n]*\n+## Notes\n+## TODO\n+## Decisions\s*$/)&&(c+="\n\n"+e)}return c}if(c.combined){const t=generateDocDialect(e,s);return`${c.combined}\n\n${t}`}return generateDocDialect(e,s)}
function computeSignature(t,e){const s=[];for(const n of(e.functions||[]).filter(e=>e.file===t))s.push(`F:${n.exported?"e":""}:${n.name}(${n.params?.join(",")||""})`);for(const n of(e.classes||[]).filter(e=>e.file===t)){const t=n.methods?.sort().join(",")||"";s.push(`C:${n.name}:${n.extends||""}:${t}`)}return s.sort(),u("md5").update(s.join("|")).digest("hex").slice(0,8)}
function parseCtxDescriptions(t){const e=new Map;for(const s of t.split("\n")){const t=s.trim();if(!t||t.startsWith("---")||t.startsWith("@sig")||t.startsWith("@enrich")||t.startsWith("Rules:")||t.startsWith("Save this")||t.startsWith("CALLS→")||t.startsWith("R→")||t.startsWith("W→"))continue;
const n=t.match(/^(PATTERNS|EDGE_CASES):\s*(.+)/);if(n&&"{DESCRIBE}"!==n[2]){e.set(n[1],n[2]);continue}const o=t.match(/^(?:export\s+)?(?:class\s+)?\.?([\w]+)\([^)]*\)(?:[^|]*?)\|(.+)/);if(o&&"{DESCRIBE}"!==o[2]){e.set(o[1],o[2]);continue}const c=t.match(/^class\s+([\w]+)[^|]*\|[^|]*\|(.+)/);c&&"{DESCRIBE}"!==c[2]&&e.set(c[1],c[2])}return e}
export function checkStaleness(e,s){const n=r(e,".context"),o=[];
let c=0,i=0;for(const{relPath:e,absPath:r}of walkCtxFiles(n,n))try{const e=t(r,"utf-8"),n=e.match(/@sig\s+(\w+)/),a=e.match(/^--- (.+) ---/m);if(!n||!a){i++;continue}computeSignature(a[1],s)!==n[1]?o.push(a[1]):c++}catch{}for(const{absPath:n}of walkCtxFiles(e,e).filter(t=>!t.relPath.startsWith(".context")))try{const e=t(n,"utf-8"),r=e.match(/@sig\s+(\w+)/),a=e.match(/^--- (.+) ---/m);if(!r||!a){i++;continue}computeSignature(a[1],s)!==r[1]?o.push(a[1]):c++}catch{}return{stale:o,fresh:c,unknown:i}}
function buildFileTemplate(t,e,s,n,o){const c=[`--- ${t} ---`,`@sig ${computeSignature(t,n)}`],r=o||new Map,i={};for(const e of n.functions||[])e.file===t&&(i[e.name]=e);
const a={};for(const e of n.classes||[])e.file===t&&(a[e.name]=e);for(const t of e){const e=s.reverseLegend[t.shortName]||t.shortName;if("C"===t.t){const n=a[e]||{},o=t.x?` extends ${t.x}`:"",i=t.m?.length||0,l=t.$?.length||0,h=[];i>0&&h.push(`${i}m`),l>0&&h.push(`${l}$`);
const f=r.get(e)||"{DESCRIBE}";if(c.push(`class ${e}${o}|${h.join(",")}|${f}`),t.m)for(const e of t.m){const t=s.reverseLegend[e]||e,n=r.get(t)||"{DESCRIBE}";c.push(`  .${t}()|${n}`)}n.calls?.length>0&&c.push(`  CALLS→${n.calls.slice(0,8).join(",")}`),n.dbReads?.length>0&&c.push(`  R→${n.dbReads.join(",")}`),n.dbWrites?.length>0&&c.push(`  W→${n.dbWrites.join(",")}`)}else if("F"===t.t){const s=i[e]||{},n=t.e?"export ":"",o=s.params?.length>0?s.params.join(","):"",a=s.returns?`→${s.returns}`:"",l=s.calls?.slice(0,6)||[],h=l.length>0?`→${l.join(",")}`:"",f=r.get(e)||"{DESCRIBE}";c.push(`${n}${e}(${o})${a}${h}|${f}`),s.dbReads?.length>0&&c.push(`  R→${s.dbReads.join(",")}`),s.dbWrites?.length>0&&c.push(`  W→${s.dbWrites.join(",")}`)}}const l=r.get("PATTERNS")||"{DESCRIBE}",h=r.get("EDGE_CASES")||"{DESCRIBE}";c.push(`PATTERNS: ${l}`),c.push(`EDGE_CASES: ${h}`);return c.join("\n").includes("{DESCRIBE}")&&c.splice(2,0,`@enrich: Replace each {DESCRIBE} below. Read ${t} for context.`,"  Rules: max 80ch, pipe|separated, abbrev (fn/ret/cfg/init/auth/db/msg).","  Save this file after filling all markers. Remove @enrich lines when done."),c.join("\n")}
export async function generateContextFiles(t,e,c,a={}){const{overwrite:l=!1,scope:h="all"}=a,u=r(e,".context"),p=[],m=[],d={};s(u)||n(u,{recursive:!0});
const $=r(u,"project.ctx");if(!s($)||l){const s=i(e),{stats:n}=t,c=[];n.files>0&&c.push(`${n.files} files`),n.classes>0&&c.push(`${n.classes} classes`),n.functions>0&&c.push(`${n.functions} functions`);
let r=[`=== PROJECT: ${s} ===`,"ARCH: {DESCRIBE}","FLOW: {DESCRIBE}",`STATS: ${c.join("|")}`].join("\n")+"\n";o($,r,"utf-8"),p.push("project.ctx"),d["project.ctx"]=r}else m.push("project.ctx");
const x={};for(const[e,s]of Object.entries(t.nodes)){const t=s.f;t&&(x[t]||(x[t]=[]),x[t].push({shortName:e,...s}))}let g=null;if("focus"===h)try{const t=f("git diff --name-only HEAD~5",{cwd:e,encoding:"utf-8"});g=new Set(t.split("\n").filter(t=>t.endsWith(".js")||t.endsWith(".mjs")||t.endsWith(".ts")).map(t=>t.trim()).filter(Boolean))}catch{g=null}else Array.isArray(h)&&(g=new Set(h));
const j=Object.entries(x).filter(([t])=>!g||g.has(t));for(let s=0;s<j.length;s+=5){const n=j.slice(s,s+5),o=await Promise.allSettled(n.map(([s,n])=>processFileCtx(s,n,t,c,u,e,l)));for(const t of o)if("fulfilled"===t.status&&t.value){const{action:e,path:s,template:n}=t.value;"created"===e?(p.push(s),d[s]=n):m.push(s)}}const C={created:p,skipped:m};return p.length>0&&(C.templates=d),C}
async function processFileCtx(e,c,h,f,u,g,j){const C=i(e,a(e))+".ctx",E=l(e),S=r(u,E),D=r(S,C),b=r(E,C),R=r(g,E,C);if((s(D)||s(R))&&!j)return{action:"skipped",path:b};
let W;s(S)||n(S,{recursive:!0});
const P=s(R)?R:s(D)?D:null;if(P&&j)try{W=parseCtxDescriptions(t(P,"utf-8"))}catch{}let w=buildFileTemplate(e,c,h,f,W);o(D,w+"\n","utf-8");try{const n=r(g,e);if(s(n)&&e.endsWith(".js")){const s=t(n,"utf-8"),o=m(s),c=d(s,e),r=$(s,e,"tests"),i=x(s,e);p(u,e,{sig:o,contentHash:o,complexity:c,undocumented:r,jsdocIssues:i})}}catch{}const y=i(e,a(e))+".ctx.md",v=r(S,y);if(!s(v)){const t=`# ${i(e)}\n\n## Notes\n\n## TODO\n\n## Decisions\n`;o(v,t,"utf-8")}return{action:"created",path:b,template:w}}