const e=new Set(["select","from","where","and","or","not","in","on","as","join","left","right","inner","outer","cross","full","group","order","by","having","limit","offset","union","all","distinct","case","when","then","else","end","null","true","false","is","between","like","ilike","exists","any","some","set","values","into","table","create","alter","drop","index","primary","key","foreign","references","constraint","default","check","unique","if","begin","commit","rollback","transaction","returning","conflict","nothing","do","update","cascade","restrict","lateral","each","row","with","recursive","only","integer","int","bigint","smallint","serial","bigserial","text","varchar","char","character","boolean","bool","timestamp","timestamptz","date","time","timetz","interval","numeric","decimal","real","float","double","json","jsonb","uuid","bytea","inet","cidr","macaddr","array","point","line","box","circle","polygon","path","count","sum","avg","min","max","coalesce","cast","extract","now","current_timestamp","current_date","generate_series","unnest","string_agg","array_agg","row_number","rank","dense_rank","over","partition","asc","desc","nulls","first","last","filter","columns","rows","tables","schema","schemas","information_schema","pg_catalog","pg_tables","pg_class"]);
export function isSQLString(e){return!(!e||"string"!=typeof e)&&/^\s*(SELECT|INSERT|UPDATE|DELETE|WITH|CREATE\s+TABLE)\b/i.test(e)}
function isValidTableName(t){return!(!t||t.length<2)&&(!e.has(t.toLowerCase())&&(!!/^[a-zA-Z_]\w*$/.test(t)&&(!/^[A-Z][A-Z_]*$/.test(t)&&(!/^[A-Z][a-z]/.test(t)&&!/^(pg_|jsonb_|array_|string_|regexp_)/.test(t)))))}
export function extractSQLFromString(e){if(!e||"string"!=typeof e)return{reads:[],writes:[]};
const t=new Set,n=new Set,s=e.replace(/--[^\n]*/g,"").replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").trim(),a=/\bFROM\s+([a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)?)/gi;
let r;for(;null!==(r=a.exec(s));){if(s.slice(r.index+r[0].length).trimStart().startsWith("("))continue;
const e=r[1].split(".").pop();isValidTableName(e)&&t.add(e)}const i=/\bJOIN\s+([a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)?)/gi;for(;null!==(r=i.exec(s));){if(s.slice(r.index+r[0].length).trimStart().startsWith("("))continue;
const e=r[1].split(".").pop();isValidTableName(e)&&t.add(e)}const o=/\bINSERT\s+INTO\s+([a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)?)/gi;for(;null!==(r=o.exec(s));){const e=r[1].split(".").pop();isValidTableName(e)&&n.add(e)}const l=/\bUPDATE\s+([a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)?)/gi;for(;null!==(r=l.exec(s));){const e=r[1].split(".").pop();isValidTableName(e)&&n.add(e)}const c=/\bDELETE\s+FROM\s+([a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)?)/gi;for(;null!==(r=c.exec(s));){const e=r[1].split(".").pop();isValidTableName(e)&&n.add(e)}for(const e of n)if(/\bDELETE\s+FROM\s+/i.test(s)){const n=s.match(/\bDELETE\s+FROM\s+([a-zA-Z_]\w*)/i);if(n){const s=n[1].split(".").pop();e===s&&t.delete(s)}}return{reads:[...t],writes:[...n]}}
export function parseSQL(e="",t=""){const n={file:t,classes:[],functions:[],imports:[],exports:[],tables:[]};if(!e)return n;
const s=/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:[a-zA-Z_]\w*\.)?([a-zA-Z_]\w*)\s*\(([\s\S]*?)\);/gi;
let a;for(;null!==(a=s.exec(e));){const s=a[1],r=a[2],i=e.substring(0,a.index).split("\n").length,o=parseColumns(r);n.tables.push({name:s,columns:o,file:t,line:i})}return n}
function parseColumns(t){const n=[],s=splitByTopLevelComma(t);for(const t of s){const s=t.trim();if(/^\s*(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT|EXCLUDE)\b/i.test(s))continue;
const a=s.match(/^([a-zA-Z_]\w*)\s+([A-Za-z]\w*(?:\s*\([^)]*\))?(?:\s*\[\])?)/);if(a){const t=a[1],s=a[2].trim();e.has(t.toLowerCase())||n.push({name:t,type:s})}}return n}
function splitByTopLevelComma(e){const t=[];
let n="",s=0;for(let a=0;a<e.length;a++){const r=e[a];if("("===r)s++;else if(")"===r)s--;else if(","===r&&0===s){t.push(n),n="";continue}n+=r}return n.trim()&&t.push(n),t}
export function extractSQLFromCode(e){const t=new Set,n=new Set;if(!e)return{reads:[],writes:[]};
const s=[/"""([\s\S]*?)"""/g,/'''([\s\S]*?)'''/g,/`([\s\S]*?)`/g,/"((?:[^"\\]|\\.)*)"/g,/'((?:[^'\\]|\\.)*)'/g];for(const a of s){let s;for(;null!==(s=a.exec(e));){const e=s[1];if(isSQLString(e)){const s=extractSQLFromString(e);s.reads.forEach(e=>t.add(e)),s.writes.forEach(e=>n.add(e))}}}const a=extractORMFromCode(e);return a.reads.forEach(e=>t.add(e)),a.writes.forEach(e=>n.add(e)),{reads:[...t],writes:[...n]}}const t=new Set(["findmany","findfirst","findunique","findraw","findall","findone","findbypk","findandcountall","count","aggregate","groupby","select","where","first","pluck"]),n=new Set(["create","createmany","update","updatemany","upsert","delete","deletemany","destroy","bulkcreate","insert","del","truncate"]);
export function extractORMFromCode(e){const s=new Set,a=new Set;if(!e)return{reads:[],writes:[]};
const r=/\bprisma\.(\w+)\.(findMany|findFirst|findUnique|findRaw|create|createMany|update|updateMany|upsert|delete|deleteMany|count|aggregate|groupBy)\s*\(/g;
let i;for(;null!==(i=r.exec(e));){const e=i[1],r=i[2].toLowerCase();if(e.startsWith("$"))continue;
const o=e;t.has(r)?s.add(o):n.has(r)&&a.add(o)}const o=/\b([A-Z][a-zA-Z]+)\.(findAll|findOne|findByPk|findAndCountAll|create|bulkCreate|update|destroy|count|sum|min|max)\s*\(/g;for(;null!==(i=o.exec(e));){const e=i[1],r=i[2].toLowerCase();if(["Promise","Object","Array","Map","Set","Date","Error","JSON","Math","Buffer","RegExp","Symbol","String","Number","Boolean","Request","Response","Console"].includes(e))continue;
const o=e.toLowerCase();t.has(r)?s.add(o):n.has(r)&&a.add(o)}const l=/\bknex\s*\(\s*['"](\w+)['"]\s*\)/g;for(;null!==(i=l.exec(e));){const t=i[1];if(isValidTableName(t)){const n=e.slice(i.index,i.index+200);/\.(insert|update|del|delete|truncate)\s*\(/i.test(n)?a.add(t):s.add(t)}}const c=/\.(from|into|table)\s*\(\s*['"](\w+)['"]\s*\)/g;for(;null!==(i=c.exec(e));){const e=i[1].toLowerCase(),t=i[2];isValidTableName(t)&&("into"===e?a.add(t):s.add(t))}return{reads:[...s],writes:[...a]}}