// @ctx .context/src/large-files.ctx
import{readFileSync as s,readdirSync as t,statSync as e}from"fs";import{join as n,relative as i,resolve as r}from"path";import{parse as l}from"../vendor/acorn.mjs";import*as o from"../vendor/walk.mjs";import{shouldExcludeDir as a,shouldExcludeFile as c,parseGitignore as u}from"./filters.js";function findJSFiles(s,r=s){s===r&&u(r);
const l=[];try{for(const o of t(s)){const t=n(s,o),u=i(r,t);e(t).isDirectory()?a(o,u)||l.push(...findJSFiles(t,r)):!o.endsWith(".js")||o.endsWith(".css.js")||o.endsWith(".tpl.js")||c(o,u)||l.push(t)}}catch(s){}return l}
function analyzeFile(t,e){const n=s(t,"utf-8"),r=i(e,t),a=n.split("\n").length;
let c,u=0,p=0,f=0;try{c=l(n,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(s){return{file:r,lines:a,functions:0,classes:0,exports:0,rating:"ok",reasons:[]}}o.simple(c,{FunctionDeclaration(){u++},ArrowFunctionExpression(s){"BlockStatement"===s.body.type&&u++},ClassDeclaration(){p++},ExportNamedDeclaration(){f++},ExportDefaultDeclaration(){f++}});
const h=[];
let d=0;a>500?(d+=2,h.push(`${a} lines (>500)`)):a>300&&(d+=1,h.push(`${a} lines (>300)`)),u>15?(d+=2,h.push(`${u} functions (>15)`)):u>10&&(d+=1,h.push(`${u} functions (>10)`)),p>3?(d+=2,h.push(`${p} classes (>3)`)):p>1&&(d+=1,h.push(`${p} classes (>1)`)),f>10?(d+=2,h.push(`${f} exports (>10)`)):f>5&&(d+=1,h.push(`${f} exports (>5)`));
let g="ok";return d>=4?g="critical":d>=2&&(g="warning"),{file:r,lines:a,functions:u,classes:p,exports:f,rating:g,reasons:h}}
export async function getLargeFiles(s,t={}){const e=t.onlyProblematic||!1,n=r(s),i=findJSFiles(s);
let l=i.map(s=>analyzeFile(s,n));e&&(l=l.filter(s=>"ok"!==s.rating)),l.sort((s,t)=>t.lines-s.lines);
const o={totalFiles:i.length,ok:l.filter(s=>"ok"===s.rating).length,warning:l.filter(s=>"warning"===s.rating).length,critical:l.filter(s=>"critical"===s.rating).length,totalLines:l.reduce((s,t)=>s+t.lines,0),avgLines:l.length>0?Math.round(l.reduce((s,t)=>s+t.lines,0)/l.length):0};return{total:l.length,stats:o,items:l.slice(0,30)}}