import{readFileSync as e,readdirSync as t,statSync as s,existsSync as n}from"fs";import{join as r,relative as o,resolve as i}from"path";import{parse as a}from"../vendor/acorn.mjs";import*as c from"../vendor/walk.mjs";import{shouldExcludeDir as l,shouldExcludeFile as p,parseGitignore as u}from"./filters.js";import{parseTypeScript as f}from"./lang-typescript.js";import{parsePython as d}from"./lang-python.js";import{parseGo as m}from"./lang-go.js";import{parseSQL as h,extractSQLFromString as y,isSQLString as g}from"./lang-sql.js";
const x=[".js",".ts",".tsx",".py",".go",".sql"];
export async function parseFile(e,t){const s={file:t,classes:[],functions:[],imports:[],exports:[]},n=[];
let r;try{r=a(e,{ecmaVersion:"latest",sourceType:"module",locations:!0,onComment:n})}catch(e){return console.warn(`Parse error in ${t}:`,e.message),s}const o=buildJSDocTypeMap(n,e),i=new Set;c.simple(r,{ImportDeclaration(e){for(const t of e.specifiers)"ImportDefaultSpecifier"===t.type?s.imports.push(t.local.name):"ImportSpecifier"===t.type&&s.imports.push(t.imported.name)},ExportNamedDeclaration(e){if(e.declaration)if(e.declaration.id)i.add(e.declaration.id.name);else if(e.declaration.declarations)for(const t of e.declaration.declarations)i.add(t.id.name);if(e.specifiers)for(const t of e.specifiers)i.add(t.exported.name)},ExportDefaultDeclaration(e){e.declaration&&e.declaration.id&&i.add(e.declaration.id.name)},ClassDeclaration(e){const n={name:e.id.name,extends:e.superClass?e.superClass.name:null,methods:[],properties:[],calls:[],dbReads:[],dbWrites:[],file:t,line:e.loc.start.line};for(const t of e.body.body)if("MethodDefinition"===t.type&&"constructor"!==t.key.name)n.methods.push(t.key.name),extractCallsAndSQL(t.value.body,n.calls,n.dbReads,n.dbWrites);else if("PropertyDefinition"===t.type){if("init$"===t.key.name&&t.value&&"ObjectExpression"===t.value.type)for(const e of t.value.properties)e.key&&e.key.name&&n.properties.push(e.key.name)}s.classes.push(n)},FunctionDeclaration(e){if(e.id){const n=e.params.map(e=>"Identifier"===e.type?e.name:"AssignmentPattern"===e.type&&"Identifier"===e.left.type?e.left.name+"=":"RestElement"===e.type&&"Identifier"===e.argument.type?"..."+e.argument.name:"ObjectPattern"===e.type?"options":"?"),r=findJSDocForNode(o,e.loc.start.line),i=enrichParamsWithTypes(n,r),a={name:e.id.name,exported:!1,params:i,async:e.async||!1,returns:r?.returns||null,calls:[],dbReads:[],dbWrites:[],file:t,line:e.loc.start.line};extractCallsAndSQL(e.body,a.calls,a.dbReads,a.dbWrites),s.functions.push(a)}}});for(const e of s.functions)e.exported=i.has(e.name);return s.exports=[...i],s}const b=new Set(["query","execute","raw","exec","queryFile","none","one","many","any","oneOrNone","manyOrNone","result"]);function extractCallsAndSQL(e,t,s,n){e&&c.simple(e,{CallExpression(e){const r=e.callee;if("MemberExpression"===r.type){const e=r.object,s=r.property;if("Identifier"===s.type)if("Identifier"===e.type){const n=`${e.name}.${s.name}`;t.includes(n)||t.push(n)}else if("MemberExpression"===e.type&&"Identifier"===e.property.type){const n=`${e.property.name}.${s.name}`;t.includes(n)||t.push(n)}else if("ThisExpression"===e.type){const e=s.name;t.includes(e)||t.push(e)}}else if("Identifier"===r.type){const e=r.name;t.includes(e)||t.push(e)}if(s&&n){const t=getCallMethodName(e);if(t&&b.has(t)&&e.arguments.length>0){const t=extractStringValue(e.arguments[0]);if(t&&g(t)){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}}}},TaggedTemplateExpression(e){if(!s||!n)return;
const t=getTagName(e.tag);if(t&&/sql/i.test(t)){const t=templateToString(e.quasi);if(t){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}}},TemplateLiteral(e){if(!s||!n)return;
const t=templateToString(e);if(t&&g(t)){const e=y(t);e.reads.forEach(e=>{s.includes(e)||s.push(e)}),e.writes.forEach(e=>{n.includes(e)||n.push(e)})}},Literal(e){if(s&&n&&"string"==typeof e.value&&g(e.value)){const t=y(e.value);t.reads.forEach(e=>{s.includes(e)||s.push(e)}),t.writes.forEach(e=>{n.includes(e)||n.push(e)})}}})}
function getTagName(e){return"Identifier"===e.type?e.name:"MemberExpression"===e.type&&"Identifier"===e.property.type?e.property.name:null}
function getCallMethodName(e){const t=e.callee;return"MemberExpression"===t.type&&"Identifier"===t.property.type?t.property.name:null}
function extractStringValue(e){return e?"Literal"===e.type&&"string"==typeof e.value?e.value:"TemplateLiteral"===e.type?templateToString(e):null:null}
function templateToString(e){if(!e||!e.quasis)return"";
let t="";for(let s=0;s<e.quasis.length;s++)t+=e.quasis[s].value.cooked||e.quasis[s].value.raw||"",s<e.expressions?.length&&(t+="$"+(s+1));return t}
export function discoverSubProjects(a){const c=i(a),l=[],p=["packages","apps","services","modules","libs","plugins"];for(const i of p){const a=r(c,i);if(n(a))try{for(const i of t(a)){const t=r(a,i),p=r(t,"package.json");if(s(t).isDirectory()&&n(p))try{const s=JSON.parse(e(p,"utf-8"));l.push({name:s.name||i,path:o(c,t),absolutePath:t})}catch{l.push({name:i,path:o(c,t),absolutePath:t})}}}catch{}}return l}
export async function parseProject(t,s={}){const n={files:[],classes:[],functions:[],imports:[],exports:[],tables:[]},a=i(t),c=findJSFiles(t);for(const t of c)try{const s=e(t,"utf-8"),r=o(a,t),i=await parseFileByExtension(s,r);n.files.push(r),n.classes.push(...i.classes),n.functions.push(...i.functions),n.imports.push(...i.imports),n.exports.push(...i.exports),i.tables?.length&&n.tables.push(...i.tables)}catch(e){}if(s.recursive){const e=discoverSubProjects(t);n.subProjects=[];for(const t of e)try{const e=await parseProject(t.absolutePath);for(const s of e.files)n.files.push(r(t.path,s));for(const s of e.classes)s.file=r(t.path,s.file),n.classes.push(s);for(const s of e.functions)s.file=r(t.path,s.file),n.functions.push(s);n.imports.push(...e.imports),n.exports.push(...e.exports),e.tables?.length&&n.tables.push(...e.tables),n.subProjects.push({name:t.name,path:t.path,files:e.files.length})}catch{}}return n.imports=[...new Set(n.imports)],n.exports=[...new Set(n.exports)],n}
async function parseFileByExtension(e,t){return t.endsWith(".sql")?h(e,t):t.endsWith(".py")?d(e,t):t.endsWith(".go")?m(e,t):t.endsWith(".ts")||t.endsWith(".tsx")?f(e,t):parseFile(e,t)}
function isSourceFile(e){return!e.endsWith(".css.js")&&!e.endsWith(".tpl.js")&&x.some(t=>e.endsWith(t))}
export function findJSFiles(e,n=e){e===n&&u(n);
const i=[];try{for(const a of t(e)){const t=r(e,a),c=s(t),u=o(n,e);c.isDirectory()?l(a,u)||i.push(...findJSFiles(t,n)):isSourceFile(a)&&(p(a,u)||i.push(t))}}catch(t){console.warn(`Cannot read directory ${e}:`,t.message)}return i}
export function findAllProjectFiles(e,n=e){e===n&&u(n);
const a=[],c=i(n);try{for(const i of t(e)){const t=r(e,i),u=s(t),f=o(c,e);u.isDirectory()?l(i,f)||a.push(...findAllProjectFiles(t,n)):p(i,f)||a.push(o(c,t))}}catch(t){console.warn(`Cannot read directory ${e}:`,t.message)}return a}
function buildJSDocTypeMap(e,t){const s=new Map;for(const n of e){if("Block"!==n.type||!n.value.startsWith("*"))continue;
const e="/*"+n.value+"*/",r=t.slice(0,n.end).split("\n").length,o=[],i=/@param\s+\{/g;
let a;for(;null!==(a=i.exec(e));){let t=1,s=a.index+a[0].length;for(;s<e.length&&t>0;)"{"===e[s]?t++:"}"===e[s]&&t--,s++;if(0!==t)continue;
const n=e.slice(a.index+a[0].length,s-1),r=e.slice(s).match(/^\s+(\[?\w+(?:\.\w+)*\]?)/);if(!r)continue;
let i=r[1];i.startsWith("[")&&(i=i.slice(1)),i.endsWith("]")&&(i=i.slice(0,-1)),i.includes(".")||o.push({name:i,type:n})}let c=null;
const l=e.match(/@returns?\s+\{([^}]+)\}/);l&&(c=l[1]),(o.length>0||c)&&s.set(r,{params:o,returns:c})}return s}
function findJSDocForNode(e,t){for(let s=1;s<=3;s++){const n=e.get(t-s);if(n)return n}return null}
function enrichParamsWithTypes(e,t){if(!t||0===t.params.length)return e;
const s=new Map;for(const e of t.params)s.set(e.name,e.type);return e.map(e=>{const t=e.startsWith("..."),n=e.endsWith("=");
let r=e;t&&(r=r.slice(3)),n&&(r=r.slice(0,-1));
let o=s.get(r);if(!o)return e;o.startsWith("...")&&(o=o.slice(3));return`${t?"...":""}${r}:${o}${n?"=":""}`})}