// @ctx .context/src/undocumented.ctx
import{readFileSync as e,readdirSync as t,statSync as n}from"fs";import{join as s,relative as o,resolve as i}from"path";import{parse as c}from"../vendor/acorn.mjs";import*as r from"../vendor/walk.mjs";import{shouldExcludeDir as l,shouldExcludeFile as a,parseGitignore as u}from"./filters.js";function findJSFiles(e,i=e){e===i&&u(i);
const c=[];try{for(const r of t(e)){const t=s(e,r),u=o(i,t);n(t).isDirectory()?l(r,u)||c.push(...findJSFiles(t,i)):!r.endsWith(".js")||r.endsWith(".css.js")||r.endsWith(".tpl.js")||a(r,u)||c.push(t)}}catch(e){}return c}
function extractComments(e){const t=[],n=/\/\*\*[\s\S]*?\*\//g;
let s;for(;null!==(s=n.exec(e));){const n=e.slice(0,s.index+s[0].length).split("\n").length;t.push({text:s[0],endLine:n})}return t}
function findJSDocBefore(e,t){for(const n of e){const e=t-n.endLine;if(e>=0&&e<=2)return n.text}return null}
function checkMissing(e,t){const n=[];return e?("params"!==t&&"all"!==t||(e.includes("@param")||n.push("@param"),e.includes("@returns")||e.includes("@return")||n.push("@returns")),n):("all"===t&&n.push("description"),"params"!==t&&"all"!==t||n.push("@param","@returns"),n)}const d=["constructor","connectedCallback","disconnectedCallback","attributeChangedCallback","renderCallback"];
export function checkUndocumentedFile(e,t,n){const s=[];
let o;try{o=c(e,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(e){return s}const i=extractComments(e);return r.simple(o,{ClassDeclaration(e){const o=e.id?.name||"Anonymous";"all"===n&&(findJSDocBefore(i,e.loc.start.line)||s.push({name:o,type:"class",file:t,line:e.loc.start.line,reason:"No JSDoc"}));for(const c of e.body.body)if("MethodDefinition"===c.type){const e=c.key.name||c.key.value;if("get"===c.kind||"set"===c.kind)continue;if(e?.startsWith("_"))continue;if(d.includes(e))continue;
const r=checkMissing(findJSDocBefore(i,c.loc.start.line),n);r.length>0&&s.push({name:`${o}.${e}`,type:"method",file:t,line:c.loc.start.line,reason:r.join(", ")})}},FunctionDeclaration(e){if(!e.id)return;
const o=e.id.name;if(o.startsWith("_"))return;
const c=checkMissing(findJSDocBefore(i,e.loc.start.line),n);c.length>0&&s.push({name:o,type:"function",file:t,line:e.loc.start.line,reason:c.join(", ")})}}),s}
export function getUndocumented(t,n="tests"){const s=i(t),c=findJSFiles(t),r=[];for(const t of c){let i;try{i=e(t,"utf-8")}catch(e){continue}const c=checkUndocumentedFile(i,o(s,t),n);r.push(...c)}return r}
export function getUndocumentedSummary(e,t="tests"){const n=getUndocumented(e,t),s={class:n.filter(e=>"class"===e.type).length,function:n.filter(e=>"function"===e.type).length,method:n.filter(e=>"method"===e.type).length},o={};for(const e of n)o[e.reason]=(o[e.reason]||0)+1;return{total:n.length,byType:s,byReason:o,items:n.slice(0,20)}}