import{readFileSync as t,readdirSync as e,statSync as n}from"fs";import{join as o,relative as s,resolve as c}from"path";import{parse as i}from"../vendor/acorn.mjs";import*as r from"../vendor/walk.mjs";import{shouldExcludeDir as l,shouldExcludeFile as a,parseGitignore as u}from"./filters.js";function findJSFiles(t,c=t){t===c&&u(c);
const i=[];try{for(const r of e(t)){const e=o(t,r),u=s(c,e);n(e).isDirectory()?l(r,u)||i.push(...findJSFiles(e,c)):!r.endsWith(".js")||r.endsWith(".css.js")||r.endsWith(".tpl.js")||a(r,u)||i.push(e)}}catch(t){}return i}
function extractComments(t){const e=[],n=/\/\*\*[\s\S]*?\*\//g;
let o;for(;null!==(o=n.exec(t));){const n=t.slice(0,o.index+o[0].length).split("\n").length;e.push({text:o[0],endLine:n})}return e}
function findJSDocBefore(t,e){for(const n of t){const t=e-n.endLine;if(t>=0&&t<=2)return n.text}return null}
function checkMissing(t,e){const n=[];return t?("params"!==e&&"all"!==e||(t.includes("@param")||n.push("@param"),t.includes("@returns")||t.includes("@return")||n.push("@returns")),n):("all"===e&&n.push("description"),"params"!==e&&"all"!==e||n.push("@param","@returns"),n)}const f=["constructor","connectedCallback","disconnectedCallback","attributeChangedCallback","renderCallback"];
export function checkUndocumentedFile(t,e,n){const o=[];
let s;try{s=i(t,{ecmaVersion:"latest",sourceType:"module",locations:!0})}catch(t){return o}const c=extractComments(t);return r.simple(s,{ClassDeclaration(t){const s=t.id?.name||"Anonymous";if("all"===n){findJSDocBefore(c,t.loc.start.line)||o.push({name:s,type:"class",file:e,line:t.loc.start.line,reason:"No JSDoc"})}for(const i of t.body.body)if("MethodDefinition"===i.type){const t=i.key.name||i.key.value;if("get"===i.kind||"set"===i.kind)continue;if(t?.startsWith("_"))continue;if(f.includes(t))continue;
const r=checkMissing(findJSDocBefore(c,i.loc.start.line),n);r.length>0&&o.push({name:`${s}.${t}`,type:"method",file:e,line:i.loc.start.line,reason:r.join(", ")})}},FunctionDeclaration(t){if(!t.id)return;
const s=t.id.name;if(s.startsWith("_"))return;
const i=checkMissing(findJSDocBefore(c,t.loc.start.line),n);i.length>0&&o.push({name:s,type:"function",file:e,line:t.loc.start.line,reason:i.join(", ")})}}),o}
export function getUndocumented(e,n="tests"){const o=c(e),i=findJSFiles(e),r=[];for(const e of i){let c;try{c=t(e,"utf-8")}catch(t){continue}const i=checkUndocumentedFile(c,s(o,e),n);r.push(...i)}return r}
export function getUndocumentedSummary(t,e="tests"){const n=getUndocumented(t,e),o={class:n.filter(t=>"class"===t.type).length,function:n.filter(t=>"function"===t.type).length,method:n.filter(t=>"method"===t.type).length},s={};for(const t of n)s[t.reason]=(s[t.reason]||0)+1;return{total:n.length,byType:o,byReason:s,items:n.slice(0,20)}}