import e from"node:http";
import t from"node:fs";
import o from"node:path";
import n from"node:crypto";import{fileURLToPath as a}from"node:url";import{WebSocketServer as s}from"ws";import{createServer as r}from"./mcp-server.js";
import c from"./event-bus.js";import{registerService as i}from"./local-gateway.js";
const l=o.dirname(a(import.meta.url)),d=o.join(l,".."),p=o.join(d,"web"),m={"symbiote-node":o.join(d,"node_modules","symbiote-node"),symbiote:o.join(d,"node_modules","@symbiotejs","symbiote")},h={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2"};function serveStatic(e,n){const a=o.normalize(e).replace(/^(\.\.[/\\])+/,""),s=a.match(/^[/\\]?vendor[/\\]([^/\\]+)[/\\]?(.*)/);
let r,c;if(s&&m[s[1]]?(c=m[s[1]],r=o.join(c,s[2]||"index.js")):(c=p,r=o.join(p,"/"===a?"index.html":a)),!r.startsWith(c))return n.writeHead(403),void n.end("Forbidden");if(t.existsSync(r)&&t.statSync(r).isDirectory()&&(r=o.join(r,"index.html")),!t.existsSync(r))return n.writeHead(404),void n.end("Not Found");
const i=o.extname(r),l=h[i]||"application/octet-stream",d=t.readFileSync(r);n.writeHead(200,{"Content-Type":l,"Cache-Control":"no-cache, no-store, must-revalidate"}),n.end(d)}
function computeWSAccept(e){return n.createHash("sha1").update(e+"258EAFA5-E914-47DA-95CA-5AB5ADF35C70").digest("base64")}
function encodeWSFrame(e){const t=Buffer.from(e,"utf8"),o=t.length;
let n;return o<126?(n=Buffer.alloc(2),n[0]=129,n[1]=o):o<65536?(n=Buffer.alloc(4),n[0]=129,n[1]=126,n.writeUInt16BE(o,2)):(n=Buffer.alloc(10),n[0]=129,n[1]=127,n.writeBigUInt64BE(BigInt(o),2)),Buffer.concat([n,t])}
function decodeWSFrame(e){if(e.length<2)return null;
const t=15&e[0],o=!!(128&e[1]);
let n=127&e[1],a=2;if(126===n){if(e.length<4)return null;n=e.readUInt16BE(2),a=4}else if(127===n){if(e.length<10)return null;n=Number(e.readBigUInt64BE(2)),a=10}if(o){if(e.length<a+4+n)return null;
const o=e.slice(a,a+4);a+=4;
const s=e.slice(a,a+n);for(let e=0;e<s.length;e++)s[e]^=o[e%4];return{opcode:t,data:s.toString("utf8"),totalLen:a+n}}return e.length<a+n?null:{opcode:t,data:e.slice(a,a+n).toString("utf8"),totalLen:a+n}}
export function startWebServer(t,a){const l=r(()=>{}),d=o.basename(o.resolve(t))||"root";
let p=1;
const m=o.resolve(t),h=n.createHash("md5").update(m).digest("hex"),u=parseInt(h.slice(0,4),16)%360,g={project:{name:d,path:m,color:`hsl(${u}, 65%, 55%)`,agents:0,pid:process.pid},skeleton:null,events:[]};function broadcastRPC(e,t){const o=JSON.stringify({jsonrpc:"2.0",method:e,params:t});for(const e of w)try{e.send(o)}catch{w.delete(e)}}
function patchState(e,t){const o=e.split(".");
let n=g;for(let e=0;e<o.length-1;e++)n=n[o[e]];n[o[o.length-1]]=t,broadcastRPC("patch",{path:e,value:t})}
async function ensureSkeleton(){if(!g.skeleton)try{g.skeleton=await l.executeTool("get_skeleton",{path:t})}catch{}return g.skeleton}const f=new Map,w=new Set;
let y=null;function hasActiveClients(){return f.size>0||w.size>0}
function resetShutdownTimer(){y&&(clearTimeout(y),y=null)}
function startShutdownTimer(){hasActiveClients()||(resetShutdownTimer(),y=setTimeout(()=>{hasActiveClients()||(console.log("[project-graph] No clients for 15 min — shutting down."),process.exit(0))},9e5))}
function touchActivity(){resetShutdownTimer(),startShutdownTimer()}
async function handleAPI(e,a,s,r){try{let s;
const c=a.get("path")||t;switch(e){case"/api/skeleton":s=await l.executeTool("get_skeleton",{path:c});break;case"/api/file":s=await l.executeTool("compact",{action:"compress_file",path:a.get("path"),beautify:!0});break;case"/api/raw-file":{const e=a.get("path");try{const{readFileSync:o}=await import("fs"),{resolve:n,relative:a}=await import("path");s={content:o(n(t,e),"utf-8"),file:e}}catch(t){s={content:`// Cannot read: ${t.message}`,file:e}}break}case"/api/docs":s=await l.executeTool("docs",{action:"get",path:c,file:a.get("file")});break;case"/api/analysis":s=await l.executeTool("analyze",{action:"full_analysis",path:c});break;case"/api/analysis-summary":s=await l.executeTool("analyze",{action:"analysis_summary",path:c});break;case"/api/deps":s=await l.executeTool("navigate",{action:"deps",symbol:a.get("symbol")});break;case"/api/usages":s=await l.executeTool("navigate",{action:"usages",symbol:a.get("symbol")});break;case"/api/expand":s=await l.executeTool("navigate",{action:"expand",symbol:a.get("symbol")});break;case"/api/chain":s=await l.executeTool("navigate",{action:"call_chain",from:a.get("from"),to:a.get("to")});break;case"/api/project-info":{const e=o.resolve(t),a=n.createHash("md5").update(e).digest("hex"),r=parseInt(a.slice(0,4),16)%360;s={name:d,path:e,color:`hsl(${r}, 65%, 55%)`,agents:f.size,pid:process.pid};break}case"/api/instances":try{const{listBackends:e}=await import("./backend-lifecycle.js");s=e()}catch{s=[{name:d,path:o.resolve(t),agents:f.size}]}break;default:return r.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-cache, no-store, must-revalidate"}),void r.end(JSON.stringify({error:"Unknown API endpoint"}))}r.writeHead(200,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Cache-Control":"no-cache"}),r.end(JSON.stringify(s))}catch(e){r.writeHead(500,{"Content-Type":"application/json","Cache-Control":"no-cache, no-store, must-revalidate"}),r.end(JSON.stringify({error:e.message}))}}startShutdownTimer(),c.on("tool:call",e=>{g.events.push(e),g.events.length>500&&g.events.shift(),broadcastRPC("event",e)}),c.on("tool:result",e=>{g.events.push(e),g.events.length>500&&g.events.shift(),broadcastRPC("event",e)});
const S=e.createServer((e,t)=>{const o=new URL(e.url,`http://localhost:${a||0}`);return"OPTIONS"===e.method?(t.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST","Access-Control-Allow-Headers":"Content-Type"}),void t.end()):o.pathname.startsWith("/api/")?(touchActivity(),void handleAPI(o.pathname,o.searchParams,0,t)):("/ws/monitor"===o.pathname&&console.log("UNEXPECTED HTTP /ws/monitor",e.headers),void serveStatic(o.pathname,t))}),v=new s({noServer:!0});v.on("connection",async e=>{w.add(e),touchActivity(),await ensureSkeleton();
const t={project:g.project,skeleton:g.skeleton};try{e.send(JSON.stringify({jsonrpc:"2.0",method:"snapshot",params:{state:t}}))}catch{}e.on("message",async t=>{let o;touchActivity();try{o=JSON.parse(t.toString())}catch{return}if(o.jsonrpc&&o.id&&o.method)if("tool"===o.method){const{name:n,args:a}=o.params||{};try{const t=await l.executeTool(n,a||{});e.send(JSON.stringify({jsonrpc:"2.0",id:o.id,result:t}))}catch(t){e.send(JSON.stringify({jsonrpc:"2.0",id:o.id,error:{code:-32e3,message:t.message}}))}}else e.send(JSON.stringify({jsonrpc:"2.0",id:o.id,error:{code:-32601,message:`Unknown method: ${o.method}`}}))}),e.on("close",()=>{w.delete(e),startShutdownTimer()}),e.on("error",()=>{w.delete(e),startShutdownTimer()})}),S.on("upgrade",(e,t,o)=>{const n=e.headers["sec-websocket-key"];if(n)if("/ws/monitor"!==e.url){if("/mcp-ws"===e.url){const e=computeWSAccept(n);t.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${e}\r\n\r\n`);
const o="agent-"+p++,a=r(e=>{try{t.write(encodeWSFrame(JSON.stringify(e)))}catch{}});f.set(t,{agentId:o,mcpServer:a,connectedAt:Date.now()}),resetShutdownTimer(),patchState("project.agents",f.size),broadcastRPC("event",{type:"agent_connect",agentId:o,agents:f.size,ts:Date.now()});
let s=Buffer.alloc(0);return t.on("data",e=>{for(s=Buffer.concat([s,e]);s.length>=2;){const n=decodeWSFrame(s);if(!n)break;if(s=s.slice(n.totalLen),8===n.opcode)return f.delete(t),patchState("project.agents",f.size),broadcastRPC("event",{type:"agent_disconnect",agentId:o,agents:f.size,ts:Date.now()}),t.end(),void(0===f.size&&startShutdownTimer());if(9===n.opcode){const o=Buffer.from(e);o[0]=240&o[0]|10,t.write(o);continue}1===n.opcode&&(async()=>{try{const e=JSON.parse(n.data),o=await a.handleMessage(e);null!==o&&t.write(encodeWSFrame(JSON.stringify(o)))}catch(e){t.write(encodeWSFrame(JSON.stringify({jsonrpc:"2.0",error:{code:-32700,message:"Parse error"}})))}})()}}),t.on("close",()=>{f.delete(t),patchState("project.agents",f.size),broadcastRPC("event",{type:"agent_disconnect",agentId:o,agents:f.size,ts:Date.now()}),0===f.size&&startShutdownTimer()}),void t.on("error",()=>{f.delete(t),0===f.size&&startShutdownTimer()})}t.destroy()}else v.handleUpgrade(e,t,o,t=>{v.emit("connection",t,e)});else t.destroy()});
const b=!a,j=a||0;return S.listen(j,"127.0.0.1",()=>{const e=S.address().port;if(b){const n=i("project-graph",e,{projectPath:o.resolve(t),projectName:d});setTimeout(()=>{const a=n.url;console.log("\n  ⬡ project-graph-mcp"),console.log("  ─────────────────────────────"),console.log(`  → ${a}`),console.log(`  → ${n.directUrl}  (direct)`),console.log(`  → Project: ${o.resolve(t)}`),console.log(`  → MCP WebSocket: ws://127.0.0.1:${e}/mcp-ws\n`)},200)}else console.log("\n  ⬡ project-graph-mcp"),console.log("  ─────────────────────────────"),console.log(`  → http://localhost:${e}/`),console.log(`  → Project: ${o.resolve(t)}`),console.log(`  → MCP WebSocket: ws://127.0.0.1:${e}/mcp-ws\n`)}),S}