// @ctx .context/src/lang/lang-python.ctx
import{stripStringsAndComments as s}from"./lang-utils.js";
export function parsePython(t="",n=""){const e={file:n,classes:[],functions:[],imports:[],exports:[]},o=s(t,{singleQuote:!0,hashComment:!0,tripleQuote:!0}).split("\n");
let l=null,i=null,c=-1;for(let s=0;s<o.length;s++){const t=o[s];if(!t.trim())continue;
const r=t.match(/^([ \t]*)/),a=r?r[1].length:0;l&&a<=c&&(l=null,c=-1),i&&0===a&&(i=null);
const u=t.match(/^class\s+([a-zA-Z_]\w*)(?:\s*\((.*?)\))?\s*:/);if(u){l={name:u[1],extends:u[2]?u[2].trim():null,methods:[],properties:[],calls:[],file:n,line:s+1},e.classes.push(l),c=a,i=null;continue}const p=t.match(/^(?:async\s+)?def\s+([a-zA-Z_]\w*)\s*\(([^)]*)\)?/);if(p){const t=(p[2]||"").split(",").map(s=>s.split(/[:=]/)[0].trim()).filter(s=>s&&"self"!==s&&"cls"!==s);i={name:p[1],exported:!0,calls:[],params:t,file:n,line:s+1},e.functions.push(i),l=null;continue}const f=t.match(/^[ \t]+(?:async\s+)?def\s+([a-zA-Z_]\w*)\s*\(/);if(f&&l&&a>c){const s=f[1];"__init__"!==s&&l.methods.push(s),i=null;continue}const m=t.match(/^\s*import\s+(.+)/);if(m){const s=m[1].split(",");for(const t of s){const s=t.trim(),n=s.match(/(?:.+)\s+as\s+([a-zA-Z_]\w*)/);n?e.imports.push(n[1]):e.imports.push(s.split(".")[0])}continue}const h=t.match(/^\s*from\s+([.\w]+)\s+import\s*(.*)/);if(h){let t=h[2];if(t.includes("(")&&!t.includes(")")){let n=s+1;for(;n<o.length;){if(t+=" "+o[n],o[n].includes(")")){s=n;break}n++}}t=t.replace(/[()]/g,"");
const n=t.split(",");for(const s of n){const t=s.trim();if(!t)continue;
const n=t.match(/(?:.+)\s+as\s+([a-zA-Z_]\w*)/);n?e.imports.push(n[1]):e.imports.push(t)}continue}const d=/([a-zA-Z_][\w.]*)\s*\(/g;
let _;
const x=new Set(["if","while","for","elif","return","yield","def","class","and","or","not","in","is","print"]);for(;null!==(_=d.exec(t));){const s=_[1];if(x.has(s))continue;
let t=s;t.startsWith("self.")&&(t=t.substring(5)),i?i.calls.includes(t)||i.calls.push(t):l&&(l.calls.includes(t)||l.calls.push(t))}}const r=t.match(/__all__\s*=\s*\[(.*?)\]/s);if(r){const s=r[1],t=/['"]([^'"]+)['"]/g;
let n;for(;null!==(n=t.exec(s));)e.exports.push(n[1]);for(const s of e.functions)s.exported=e.exports.includes(s.name)}else{for(const s of e.classes)e.exports.push(s.name);for(const s of e.functions)e.exports.push(s.name),s.exported=!0}return e.imports=[...new Set(e.imports)],e}