// @ctx .context/src/network/web-server.ctx
import e from"node:http";
import t from"node:fs";
import o from"node:path";
import n from"node:crypto";import{fileURLToPath as a}from"node:url";import{WebSocketServer as s}from"ws";import{createServer as r}from"../mcp/mcp-server.js";
import c from"../core/event-bus.js";import{registerService as i}from"./local-gateway.js";import{expandFile as l}from"../compact/expand.js";
const d=o.dirname(a(import.meta.url)),p=o.join(d,"..",".."),m=o.join(p,"web"),h={"symbiote-node":o.join(p,"node_modules","symbiote-node"),symbiote:o.join(p,"node_modules","@symbiotejs","symbiote")},u={".html":"text/html",".js":"text/javascript",".mjs":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".ico":"image/x-icon",".woff2":"font/woff2"};function serveStatic(e,n){const a=o.normalize(e).replace(/^(\.\.[/\\])+/,""),s=a.match(/^[/\\]?vendor[/\\]([^/\\]+)[/\\]?(.*)/);
let r,c;if(s&&h[s[1]]?(c=h[s[1]],r=o.join(c,s[2]||"index.js")):(c=m,r=o.join(m,"/"===a?"index.html":a)),!r.startsWith(c))return n.writeHead(403),void n.end("Forbidden");if(t.existsSync(r)&&t.statSync(r).isDirectory()&&(r=o.join(r,"index.html")),!t.existsSync(r))return n.writeHead(404),void n.end("Not Found");
const i=o.extname(r),l=u[i]||"application/octet-stream",d=t.readFileSync(r);n.writeHead(200,{"Content-Type":l,"Cache-Control":"no-cache, no-store, must-revalidate"}),n.end(d)}
function computeWSAccept(e){return n.createHash("sha1").update(e+"258EAFA5-E914-47DA-95CA-5AB5ADF35C70").digest("base64")}
function encodeWSFrame(e){const t=Buffer.from(e,"utf8"),o=t.length;
let n;return o<126?(n=Buffer.alloc(2),n[0]=129,n[1]=o):o<65536?(n=Buffer.alloc(4),n[0]=129,n[1]=126,n.writeUInt16BE(o,2)):(n=Buffer.alloc(10),n[0]=129,n[1]=127,n.writeBigUInt64BE(BigInt(o),2)),Buffer.concat([n,t])}
function decodeWSFrame(e){if(e.length<2)return null;
const t=15&e[0],o=!!(128&e[1]);
let n=127&e[1],a=2;if(126===n){if(e.length<4)return null;n=e.readUInt16BE(2),a=4}else if(127===n){if(e.length<10)return null;n=Number(e.readBigUInt64BE(2)),a=10}if(o){if(e.length<a+4+n)return null;
const o=e.slice(a,a+4);a+=4;
const s=e.slice(a,a+n);for(let e=0;e<s.length;e++)s[e]^=o[e%4];return{opcode:t,data:s.toString("utf8"),totalLen:a+n}}return e.length<a+n?null:{opcode:t,data:e.slice(a,a+n).toString("utf8"),totalLen:a+n}}
export function startWebServer(t,a){const d=r(()=>{}),p=o.basename(o.resolve(t))||"root";
let m=1;
const h=o.resolve(t),u=n.createHash("md5").update(h).digest("hex"),g=parseInt(u.slice(0,4),16)%360,f={project:{name:p,path:h,color:`hsl(${g}, 65%, 55%)`,agents:0,pid:process.pid},skeleton:null,events:[]};function broadcastRPC(e,t){const o=JSON.stringify({jsonrpc:"2.0",method:e,params:t});for(const e of y)try{e.send(o)}catch{y.delete(e)}}
function patchState(e,t){const o=e.split(".");
let n=f;for(let e=0;e<o.length-1;e++)n=n[o[e]];n[o[o.length-1]]=t,broadcastRPC("patch",{path:e,value:t})}
async function ensureSkeleton(){if(!f.skeleton)try{f.skeleton=await d.executeTool("get_skeleton",{path:t})}catch{}return f.skeleton}const w=new Map,y=new Set;
let S=null;function hasActiveClients(){return w.size>0||y.size>0}
function resetShutdownTimer(){S&&(clearTimeout(S),S=null)}
function startShutdownTimer(){hasActiveClients()||(resetShutdownTimer(),S=setTimeout(()=>{hasActiveClients()||(console.log("[project-graph] No clients for 15 min — shutting down."),process.exit(0))},9e5))}
function touchActivity(){resetShutdownTimer(),startShutdownTimer()}
async function handleAPI(e,a,s,r){try{let c;
const i=a.get("path")||t;switch(e){case"/api/skeleton":c=await d.executeTool("get_skeleton",{path:i});break;case"/api/file":{const e=a.get("path");if(e){const{resolve:n,basename:a,extname:s}=await import("path"),{readFileSync:r,existsSync:i}=await import("fs"),d=n(t,e),p=a(e,s(e))+".ctx",m=o.resolve(t,".context",o.dirname(e),p),h=i(m)?r(m,"utf-8"):null,u=await l(d,h),g=Math.ceil(u.original/4),f=Math.ceil(u.decompiled/4),w=g>0?Math.round(100*(1-f/g)):0;c={code:u.code,file:e,injected:u.injected,original:g,compressed:f,savings:w+"%"}}else c={code:"// No file specified",file:""};break}case"/api/raw-file":{const e=a.get("path");try{const{readFileSync:o}=await import("fs"),{resolve:n,relative:a}=await import("path");c={content:o(n(t,e),"utf-8"),file:e}}catch(t){c={content:`// Cannot read: ${t.message}`,file:e}}break}case"/api/docs":c=await d.executeTool("docs",{action:"get",path:i,file:a.get("file")});break;case"/api/analysis":c=await d.executeTool("analyze",{action:"full_analysis",path:i});break;case"/api/analysis-summary":c=await d.executeTool("analyze",{action:"analysis_summary",path:i});break;case"/api/deps":c=await d.executeTool("navigate",{action:"deps",symbol:a.get("symbol")});break;case"/api/usages":c=await d.executeTool("navigate",{action:"usages",symbol:a.get("symbol")});break;case"/api/expand":c=await d.executeTool("navigate",{action:"expand",symbol:a.get("symbol")});break;case"/api/chain":c=await d.executeTool("navigate",{action:"call_chain",from:a.get("from"),to:a.get("to")});break;case"/api/project-info":{const e=o.resolve(t),a=n.createHash("md5").update(e).digest("hex"),s=parseInt(a.slice(0,4),16)%360;c={name:p,path:e,color:`hsl(${s}, 65%, 55%)`,agents:w.size,pid:process.pid};break}case"/api/instances":try{const{listBackends:e}=await import("./backend-lifecycle.js");c=e()}catch{c=[{name:p,path:o.resolve(t),agents:w.size}]}break;default:return"POST"===s&&"/api/restart"===e?(r.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-cache"}),r.end(JSON.stringify({ok:!0,message:"Server restarting..."})),void setTimeout(()=>process.exit(0),200)):(r.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-cache, no-store, must-revalidate"}),void r.end(JSON.stringify({error:"Unknown API endpoint"})))}r.writeHead(200,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Cache-Control":"no-cache"}),r.end(JSON.stringify(c))}catch(e){r.writeHead(500,{"Content-Type":"application/json","Cache-Control":"no-cache, no-store, must-revalidate"}),r.end(JSON.stringify({error:e.message}))}}startShutdownTimer(),c.on("tool:call",e=>{f.events.push(e),f.events.length>500&&f.events.shift(),broadcastRPC("event",e)}),c.on("tool:result",e=>{f.events.push(e),f.events.length>500&&f.events.shift(),broadcastRPC("event",e)});
const v=e.createServer((e,t)=>{const o=new URL(e.url,`http://localhost:${a||0}`);return"OPTIONS"===e.method?(t.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST","Access-Control-Allow-Headers":"Content-Type"}),void t.end()):o.pathname.startsWith("/api/")?(touchActivity(),void handleAPI(o.pathname,o.searchParams,e.method,t)):("/ws/monitor"===o.pathname&&console.log("UNEXPECTED HTTP /ws/monitor",e.headers),void serveStatic(o.pathname,t))}),j=new s({noServer:!0});j.on("connection",async e=>{y.add(e),touchActivity(),await ensureSkeleton();
const t={project:f.project,skeleton:f.skeleton};try{e.send(JSON.stringify({jsonrpc:"2.0",method:"snapshot",params:{state:t}}))}catch{}e.on("message",async t=>{let n;touchActivity();try{n=JSON.parse(t.toString())}catch{return}if(n.jsonrpc&&n.id&&n.method)if("tool"===n.method){const{name:a,args:s}=n.params||{};try{let t;if("compact"===a&&"compact_file"===s?.action&&s?.path){const e=o.resolve(h,s.path),n=o.basename(s.path,o.extname(s.path))+".ctx",a=o.resolve(h,".context",o.dirname(s.path),n);
let r=null;try{const{readFileSync:e,existsSync:t}=await import("fs");t(a)&&(r=e(a,"utf-8"))}catch{}const c=await l(e,r),i=Math.ceil(c.original/4),d=Math.ceil(c.decompiled/4),p=i>0?Math.round(100*(1-d/i)):0;t={code:c.code,file:s.path,injected:c.injected,original:i,compressed:d,savings:p+"%"}}else t=await d.executeTool(a,s||{});e.send(JSON.stringify({jsonrpc:"2.0",id:n.id,result:t}))}catch(t){e.send(JSON.stringify({jsonrpc:"2.0",id:n.id,error:{code:-32e3,message:t.message}}))}}else e.send(JSON.stringify({jsonrpc:"2.0",id:n.id,error:{code:-32601,message:`Unknown method: ${n.method}`}}))}),e.on("close",()=>{y.delete(e),startShutdownTimer()}),e.on("error",()=>{y.delete(e),startShutdownTimer()})}),v.on("upgrade",(e,t,o)=>{const n=e.headers["sec-websocket-key"];if(n)if("/ws/monitor"!==e.url){if("/mcp-ws"===e.url){const e=computeWSAccept(n);t.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${e}\r\n\r\n`);
const o="agent-"+m++,a=r(e=>{try{t.write(encodeWSFrame(JSON.stringify(e)))}catch{}});w.set(t,{agentId:o,mcpServer:a,connectedAt:Date.now()}),resetShutdownTimer(),patchState("project.agents",w.size),broadcastRPC("event",{type:"agent_connect",agentId:o,agents:w.size,ts:Date.now()});
let s=Buffer.alloc(0);return t.on("data",e=>{for(s=Buffer.concat([s,e]);s.length>=2;){const n=decodeWSFrame(s);if(!n)break;if(s=s.slice(n.totalLen),8===n.opcode)return w.delete(t),patchState("project.agents",w.size),broadcastRPC("event",{type:"agent_disconnect",agentId:o,agents:w.size,ts:Date.now()}),t.end(),void(0===w.size&&startShutdownTimer());if(9===n.opcode){const o=Buffer.from(e);o[0]=240&o[0]|10,t.write(o);continue}1===n.opcode&&(async()=>{try{const e=JSON.parse(n.data),o=await a.handleMessage(e);null!==o&&t.write(encodeWSFrame(JSON.stringify(o)))}catch(e){t.write(encodeWSFrame(JSON.stringify({jsonrpc:"2.0",error:{code:-32700,message:"Parse error"}})))}})()}}),t.on("close",()=>{w.delete(t),patchState("project.agents",w.size),broadcastRPC("event",{type:"agent_disconnect",agentId:o,agents:w.size,ts:Date.now()}),0===w.size&&startShutdownTimer()}),void t.on("error",()=>{w.delete(t),0===w.size&&startShutdownTimer()})}t.destroy()}else j.handleUpgrade(e,t,o,t=>{j.emit("connection",t,e)});else t.destroy()});
const b=!a,T=a||0;return v.listen(T,"127.0.0.1",()=>{const e=v.address().port;if(b){const n=i("project-graph",e,{projectPath:o.resolve(t),projectName:p});setTimeout(()=>{const a=n.url;console.log("\n  ⬡ project-graph-mcp"),console.log("  ─────────────────────────────"),console.log(`  → ${a}`),console.log(`  → ${n.directUrl}  (direct)`),console.log(`  → Project: ${o.resolve(t)}`),console.log(`  → MCP WebSocket: ws://127.0.0.1:${e}/mcp-ws\n`)},200)}else console.log("\n  ⬡ project-graph-mcp"),console.log("  ─────────────────────────────"),console.log(`  → http://localhost:${e}/`),console.log(`  → Project: ${o.resolve(t)}`),console.log(`  → MCP WebSocket: ws://127.0.0.1:${e}/mcp-ws\n`)}),v}