import{Layout as e,LayoutTree as t,applyTheme as n}from"symbiote-node";import{CARBON as o}from"./vendor/symbiote-node/themes/carbon.js";import{state as a,subscribe as i,onEvent as s,call as r,connect as l}from"./state.js";import"./panels/file-tree.js";import"./panels/code-viewer.js";import"./panels/ctx-panel.js";import"./panels/dep-graph.js";import"./panels/health-panel.js";import"./panels/live-monitor.js";import"./panels/SettingsPanel/SettingsPanel.js";import"./components/quick-open.js";
export const state={skeleton:null,activeFile:null,ws:null,monitorEvents:[]};
const c=new URL(".",import.meta.url).href;
export async function api(e,t={}){if(a.connected&&e.startsWith("/api/")){const n=await apiViaWS(e,t);if(null!==n)return n}const n=new URLSearchParams(t).toString(),o=e.replace(/^\//,""),i=n?`${c}${o}?${n}`:`${c}${o}`,s=await fetch(i);if(!s.ok)throw new Error(`API error: ${s.status}`);return s.json()}
async function apiViaWS(e,t){const n={"/api/skeleton":{name:"get_skeleton",args:e=>({path:e.path})},"/api/file":{name:"compact",args:e=>({action:"compress_file",path:e.path,beautify:!0})},"/api/docs":{name:"docs",args:e=>({action:"get",path:e.path,file:e.file})},"/api/analysis":{name:"analyze",args:e=>({action:"full_analysis",path:e.path})},"/api/analysis-summary":{name:"analyze",args:e=>({action:"analysis_summary",path:e.path})},"/api/deps":{name:"navigate",args:e=>({action:"deps",symbol:e.symbol})},"/api/usages":{name:"navigate",args:e=>({action:"usages",symbol:e.symbol})},"/api/expand":{name:"navigate",args:e=>({action:"expand",symbol:e.symbol})},"/api/chain":{name:"navigate",args:e=>({action:"call_chain",from:e.from,to:e.to})}}[e];return n?r(n.name,n.args(t)):null}
export const events=new EventTarget;
export function emit(e,t={}){events.dispatchEvent(new CustomEvent(e,{detail:t}))}const p={"file-tree":{title:"Files",icon:"folder",component:"pg-file-tree"},"code-viewer":{title:"Code",icon:"code",component:"pg-code-viewer"},"ctx-panel":{title:"Documentation",icon:"description",component:"pg-ctx-panel"},"dep-graph":{title:"Dependencies",icon:"account_tree",component:"pg-dep-graph"},health:{title:"Health",icon:"analytics",component:"pg-health-panel"},monitor:{title:"Live Monitor",icon:"monitor_heart",component:"pg-live-monitor"},settings:{title:"Settings",icon:"settings",component:"pg-settings-panel"}},m=[{id:"explorer",icon:"folder_open",label:"Explorer"},{id:"analysis",icon:"analytics",label:"Analysis"},{id:"monitor",icon:"monitor_heart",label:"Monitor"},{id:"settings",icon:"settings",label:"Settings"}],d={explorer:()=>t.createSplit("horizontal",t.createPanel("file-tree"),t.createSplit("horizontal",t.createPanel("code-viewer"),t.createPanel("ctx-panel"),.65),.2),analysis:()=>t.createSplit("horizontal",t.createPanel("health"),t.createPanel("dep-graph"),.5),monitor:()=>t.createPanel("monitor"),settings:()=>t.createPanel("settings")};function initLayout(){n(document.documentElement,o);
const e=document.querySelector(".app-workspace"),t=document.createElement("layout-sidebar");e.prepend(t);
const a=e.querySelector(".app-content"),i=document.createElement("panel-layout");i.setAttribute("storage-key","pg-explorer-layout"),i.setAttribute("min-panel-size","150"),i.id="main-layout",a.appendChild(i),requestAnimationFrame(()=>{for(const[e,t]of Object.entries(p))i.registerPanelType(e,t);function applyRouteLayout(){const e=location.hash.replace("#","")||"explorer",t=e.indexOf("?"),n=t>=0?e.substring(0,t):e,o=n.indexOf("/"),a=o>=0?n.substring(0,o):n,s=o>=0?n.substring(o+1):"";d[a]&&i.setLayout(d[a]()),"explorer"===a&&s&&requestAnimationFrame(()=>{state.activeFile=s,emit("file-selected",{path:s,fromRoute:!0})})}t.setSections(m),window.addEventListener("hashchange",applyRouteLayout),events.addEventListener("file-selected",e=>{if(e.detail.fromRoute)return;
const t=e.detail.path;t&&history.replaceState(null,"",`#explorer/${t}`)}),localStorage.getItem("pg-explorer-layout")||i.setLayout(d.explorer()),location.hash&&"#"!==location.hash?applyRouteLayout():location.hash="explorer"})}
async function init(){initLayout(),l(),i("project",e=>{e&&(document.title=`${e.name} — Project Graph`,document.getElementById("project-name").textContent=e.name,document.documentElement.style.setProperty("--project-accent",e.color),updateAgentBadge(e.agents))}),i("skeleton",e=>{if(!e)return;state.skeleton=e;
const t=new Set;for(const n of Object.values(e.n||{}))n.f&&t.add(n.f);for(const n of Object.keys(e.X||{}))t.add(n);for(const[n,o]of Object.entries(e.f||{}))for(const e of o)t.add("./"===n?e:`${n}${e}`);for(const[n,o]of Object.entries(e.a||{}))for(const e of o)t.add("./"===n?e:`${n}${e}`);
const n=document.getElementById("project-files");n&&(n.textContent=`${t.size} files`),emit("skeleton-loaded",e)}),i("connected",e=>{const t=document.getElementById("status-indicator");t&&(t.className=e?"status connected":"status disconnected")}),s(e=>{if("agent_connect"===e.type||"agent_disconnect"===e.type)return updateAgentBadge(e.agents),void emit("agent-event",e);state.monitorEvents.push(e),state.monitorEvents.length>500&&state.monitorEvents.shift(),emit("tool-event",e)})}
function updateAgentBadge(e){let t=document.getElementById("agent-badge");if(!t){const e=document.querySelector(".app-topbar");if(!e)return;t=document.createElement("span"),t.id="agent-badge",t.className="agent-badge",e.appendChild(t)}t.textContent=e>0?`● ${e} agent${1!==e?"s":""}`:"",t.style.display=e>0?"":"none"}
function mountGlobalComponents(){document.querySelector("pg-quick-open")||document.body.appendChild(document.createElement("pg-quick-open"))}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",()=>{init(),mountGlobalComponents()}):setTimeout(()=>{init(),mountGlobalComponents()},100);