// @ctx .context/web/app.ctx
import{Layout as t,LayoutTree as n,applyTheme as o}from"symbiote-node";import{CARBON as a}from"./vendor/symbiote-node/themes/carbon.js";import{state as s,subscribe as i,onEvent as r,call as c,connect as l}from"./state.js";import"./panels/file-tree.js";import"./panels/code-viewer.js";import"./panels/ctx-panel.js";import"./panels/dep-graph.js";import"./panels/health-panel.js";import"./panels/live-monitor.js";import"./panels/SettingsPanel/SettingsPanel.js";import"./components/quick-open.js";
export const state={skeleton:null,activeFile:null,ws:null,monitorEvents:[]};
const m=new URL(".",import.meta.url).href;
export async function api(t,n={}){if(s.connected&&t.startsWith("/api/")){const o=await p(t,n);if(null!==o)return o}const o=new URLSearchParams(n).toString(),a=t.replace(/^\//,""),i=o?`${m}${a}?${o}`:`${m}${a}`,r=await fetch(i);if(!r.ok)throw new Error(`API error: ${r.status}`);return r.json()}
async function p(t,n){const o={"/api/skeleton":{name:"get_skeleton",args:t=>({path:t.path})},"/api/file":{name:"compact",args:t=>({action:"compact_file",path:t.path,beautify:!0})},"/api/docs":{name:"docs",args:t=>({action:"get",path:t.path,file:t.file})},"/api/analysis":{name:"analyze",args:t=>({action:"full_analysis",path:t.path})},"/api/analysis-summary":{name:"analyze",args:t=>({action:"analysis_summary",path:t.path})},"/api/deps":{name:"navigate",args:t=>({action:"deps",symbol:t.symbol})},"/api/usages":{name:"navigate",args:t=>({action:"usages",symbol:t.symbol})},"/api/expand":{name:"navigate",args:t=>({action:"expand",symbol:t.symbol})},"/api/chain":{name:"navigate",args:t=>({action:"call_chain",from:t.from,to:t.to})}}[t];return o?c(o.name,o.args(n)):null}
export const events=new EventTarget;
export function emit(t,n={}){events.dispatchEvent(new CustomEvent(t,{detail:n}))}const d={"file-tree":{title:"Files",icon:"folder",component:"pg-file-tree"},"code-viewer":{title:"Code",icon:"code",component:"pg-code-viewer"},"ctx-panel":{title:"Documentation",icon:"description",component:"pg-ctx-panel"},"dep-graph":{title:"Dependencies",icon:"account_tree",component:"pg-dep-graph"},health:{title:"Health",icon:"analytics",component:"pg-health-panel"},monitor:{title:"Live Monitor",icon:"monitor_heart",component:"pg-live-monitor"},settings:{title:"Settings",icon:"settings",component:"pg-settings-panel"}},u=[{id:"explorer",icon:"folder_open",label:"Explorer"},{id:"analysis",icon:"analytics",label:"Analysis"},{id:"monitor",icon:"monitor_heart",label:"Monitor"},{id:"settings",icon:"settings",label:"Settings"}],b={explorer:()=>n.createSplit("horizontal",n.createPanel("file-tree"),n.createSplit("horizontal",n.createPanel("code-viewer"),n.createPanel("ctx-panel"),.65),.2),analysis:()=>n.createSplit("horizontal",n.createPanel("health"),n.createPanel("dep-graph"),.5),monitor:()=>n.createPanel("monitor"),settings:()=>n.createPanel("settings")};function g(){o(document.documentElement,a);
const t=document.querySelector(".app-workspace"),n=document.createElement("layout-sidebar");t.prepend(n);
const s=t.querySelector(".app-content"),i=document.createElement("panel-layout");i.setAttribute("storage-key","pg-explorer-layout"),i.setAttribute("min-panel-size","150"),i.id="main-layout",s.appendChild(i),requestAnimationFrame(()=>{for(const[t,n]of Object.entries(d))i.registerPanelType(t,n);function e(){const t=location.hash.replace("#","")||"explorer",n=t.indexOf("?"),o=n>=0?t.substring(0,n):t,a=o.indexOf("/"),s=a>=0?o.substring(0,a):o,r=a>=0?o.substring(a+1):"";b[s]&&i.setLayout(b[s]()),"explorer"===s&&r&&requestAnimationFrame(()=>{state.activeFile=r,emit("file-selected",{path:r,fromRoute:!0})})}n.setSections(u),window.addEventListener("hashchange",e),events.addEventListener("file-selected",t=>{if(t.detail.fromRoute)return;
const n=t.detail.path;n&&history.replaceState(null,"",`#explorer/${n}`)}),localStorage.getItem("pg-explorer-layout")||i.setLayout(b.explorer()),location.hash&&"#"!==location.hash?e():location.hash="explorer"})}
async function f(){g(),l(),i("project",t=>{t&&(document.title=`${t.name} — Project Graph`,document.getElementById("project-name").textContent=t.name,document.documentElement.style.setProperty("--project-accent",t.color),h(t.agents))}),i("skeleton",t=>{if(!t)return;state.skeleton=t;
const n=new Set;for(const o of Object.values(t.n||{}))o.f&&n.add(o.f);for(const o of Object.keys(t.X||{}))n.add(o);for(const[o,a]of Object.entries(t.f||{}))for(const t of a)n.add("./"===o?t:`${o}${t}`);for(const[o,a]of Object.entries(t.a||{}))for(const t of a)n.add("./"===o?t:`${o}${t}`);
const o=document.getElementById("project-files");o&&(o.textContent=`${n.size} files`),emit("skeleton-loaded",t),fetch(m+"api/compression-stats").then(t=>t.json()).then(t=>{const n=document.getElementById("compression-stats");if(n&&t.compactTokens){const o=`${t.files} src · ${(t.compactTokens/1e3).toFixed(1)}K tok`;n.textContent=o,n.style.display=""}})}),i("connected",t=>{const n=document.getElementById("status-indicator");n&&(n.className=t?"status connected":"status disconnected")}),r(t=>{if("agent_connect"===t.type||"agent_disconnect"===t.type)return h(t.agents),void emit("agent-event",t);state.monitorEvents.push(t),state.monitorEvents.length>500&&state.monitorEvents.shift(),emit("tool-event",t)})}
function h(t){let n=document.getElementById("agent-badge");if(!n){const t=document.querySelector(".app-topbar");if(!t)return;n=document.createElement("span"),n.id="agent-badge",n.className="agent-badge",t.appendChild(n)}n.textContent=t>0?`● ${t} agent${1!==t?"s":""}`:"",n.style.display=t>0?"":"none"}
function y(){document.querySelector("pg-quick-open")||document.body.appendChild(document.createElement("pg-quick-open"))}"loading"===document.readyState?document.addEventListener("DOMContentLoaded",()=>{f(),y()}):setTimeout(()=>{f(),y()},100);