const t=new Set(["async","await","break","case","catch","class","const","continue","debugger","default","delete","do","else","export","extends","finally","for","from","function","if","import","in","instanceof","let","new","of","return","super","switch","this","throw","try","typeof","var","void","while","with","yield","static","get","set"]),s=new Set(["true","false","null","undefined","NaN","Infinity"]),e=new Set(["console","document","window","global","process","module","require","Promise","Array","Object","String","Number","Boolean","Map","Set","WeakMap","WeakSet","Symbol","RegExp","Error","JSON","Math","Date","parseInt","parseFloat","setTimeout","setInterval","clearTimeout","clearInterval","fetch","URL","Buffer","EventTarget","CustomEvent","HTMLElement","requestAnimationFrame","queueMicrotask"]);function esc(t){return"&"===t?"&amp;":"<"===t?"&lt;":">"===t?"&gt;":t}
export function highlight(n){const i=[],a=n.length;
let r=0;for(;r<a;){const o=n[r];if("/"===o&&"/"===n[r+1]){const t=r;for(;r<a&&"\n"!==n[r];)r++;i.push(`<span class="t-cm">${escRange(n,t,r)}</span>`);continue}if("/"===o&&"*"===n[r+1]){const t=r;for(r+=2;r<a&&("*"!==n[r]||"/"!==n[r+1]);)r++;r+=2,i.push(`<span class="t-cm">${escRange(n,t,r)}</span>`);continue}if("'"===o||'"'===o){const t=r;for(r++;r<a&&n[r]!==o;)"\\"===n[r]&&r++,r++;r++,i.push(`<span class="t-str">${escRange(n,t,r)}</span>`);continue}if("`"===o){const t=r;for(r++;r<a&&"`"!==n[r];)"\\"===n[r]&&r++,r++;r++,i.push(`<span class="t-str">${escRange(n,t,r)}</span>`);continue}if(isDigit(o)||"."===o&&r+1<a&&isDigit(n[r+1])){const t=r;if("0"!==o||"x"!==n[r+1]&&"X"!==n[r+1])for(;r<a&&(isDigit(n[r])||"."===n[r]||"e"===n[r]||"E"===n[r]||"_"===n[r]);)r++;else for(r+=2;r<a&&isHexDigit(n[r]);)r++;r<a&&"n"===n[r]&&r++,i.push(`<span class="t-num">${escRange(n,t,r)}</span>`);continue}if(isIdentStart(o)){const o=r;for(;r<a&&isIdentPart(n[r]);)r++;
const c=n.substring(o,r);
let u=r;for(;u<a&&" "===n[u];)u++;t.has(c)?i.push(`<span class="t-kw">${c}</span>`):s.has(c)?i.push(`<span class="t-lit">${c}</span>`):e.has(c)?i.push(`<span class="t-bi">${c}</span>`):"("===n[u]?i.push(`<span class="t-fn">${c}</span>`):o>0&&"."===n[o-1]?i.push(`<span class="t-prop">${c}</span>`):i.push(c);continue}i.push(esc(o)),r++}return i.join("")}
function escRange(t,s,e){let n="";for(let i=s;i<e;i++)n+=esc(t[i]);return n}
function isDigit(t){return t>="0"&&t<="9"}
function isHexDigit(t){return isDigit(t)||t>="a"&&t<="f"||t>="A"&&t<="F"}
function isIdentStart(t){return t>="a"&&t<="z"||t>="A"&&t<="Z"||"_"===t||"$"===t}
function isIdentPart(t){return isIdentStart(t)||isDigit(t)}